In [ ]:
# from datasets import load_dataset

# # Wikipedia RU
# wiki = load_dataset("wikimedia/wikipedia", "20231101.ru", split="train")
# # Save to folder
# wiki.save_to_disk("d:/Neuro_net/Projects/LLM/Gen/data/wiki_ru_20231101")

# OSCAR RU
# oscar_russian = load_dataset("oscar-corpus/oscar", "ru", split="train")

# oscar_russian

In [1]:
from datasets import load_from_disk
wiki = load_from_disk("d:/Neuro_net/Projects/LLM/Gen/data/wiki_ru_20231101")
wiki

Loading dataset from disk:   0%|          | 0/21 [00:00<?, ?it/s]

Dataset({
    features: ['id', 'url', 'title', 'text'],
    num_rows: 1945063
})

In [2]:
import pandas as pd

splits = {'train': 'sberquad/train-00000-of-00001.parquet', 'validation': 'sberquad/validation-00000-of-00001.parquet', 'test': 'sberquad/test-00000-of-00001.parquet'}
df = pd.read_parquet("hf://datasets/kuznetsoffandrey/sberquad/" + splits["test"])
# df.to_json("./data/sberquad/sberquad_test.json", orient="records", force_ascii=False)

In [208]:
import pandas as pd
df1 = pd.read_json('./data/sberquad/sberquad_train.json')
df2 = pd.read_json('./data/sberquad/sberquad_valid.json')
df3 = pd.read_json('./data/sberquad/sberquad_test.json')
df = pd.concat([df1, df2, df3], ignore_index=True)   
df

,id,title,context,question,answers
0,62310,SberChallenge,В протерозойских отложениях органические остат...,чем представлены органические остатки?,{'text': ['известковыми выделениями сине-зелён...
1,28101,SberChallenge,В протерозойских отложениях органические остат...,что найдено в кремнистых сланцах железорудной ...,"{'text': ['нитевидные водоросли, грибные нити'..."
2,48834,SberChallenge,В протерозойских отложениях органические остат...,что встречается в протерозойских отложениях?,"{'text': ['органические остатки'], 'answer_sta..."
3,83056,SberChallenge,В протерозойских отложениях органические остат...,что относится к числу древнейших растительных ...,{'text': ['скопления графито-углистого веществ...
4,5816,SberChallenge,В протерозойских отложениях органические остат...,как образовалось графито-углистое вещество?,{'text': ['в результате разложения Corycium en...
...,...,...,...,...,...
74295,31452,SberChallenge,"ФГУПы, в отличие от негосударственных юридичес...",Куда поступают прибыли от государственных пред...,"{'text': [''], 'answer_start': [-1]}"
74296,24850,SberChallenge,"ФГУПы, в отличие от негосударственных юридичес...","Чем, для государства, представляют собой ФГУПы?","{'text': [''], 'answer_start': [-1]}"
74297,996,SberChallenge,"ФГУПы, в отличие от негосударственных юридичес...",Какой статьей руководствуются предприятия при ...,"{'text': [''], 'answer_start': [-1]}"
74298,35293,SberChallenge,"ФГУПы, в отличие от негосударственных юридичес...",Какой объем прибыли поступает от унитарных пре...,"{'text': [''], 'answer_start': [-1]}"
74299,70459,SberChallenge,"ФГУПы, в отличие от негосударственных юридичес...",Какой объем денежной массы был передан ФГУП СВ...,"{'text': [''], 'answer_start': [-1]}"

In [221]:
# df["answer"] = df["answers"].apply(lambda x: x["text"][0])

# считаем длину ответа
# df["answer_len"] = df["answers"].apply(lambda x: len(x["text"][0]))
df["question_len"] = df["question"].apply(lambda x: len(x))

# сортируем по длине ответа (по убыванию)
df_sorted = df.sort_values(["context", "question_len"], ascending=False)

# удаляем дубликаты context, оставляя первый (самый длинный ответ)
df_unique = df_sorted.drop_duplicates(subset="context", keep="first")

# оставляем только нужные столбцы
df_unique = df_unique[["context", "question"]]
df_unique["context"][8694]

'представлял собой дротик — метательное копьё тяжелой пехоты, несколько укороченное и облегчённое по сравнению с копьями для конного или рукопашного боя и соответствующим образом уравновешенное для удобства метания. У римлян было два вида пилумов — короткий (2 м длиной) и тяжёлый (4—5 кг). Древко пилума заканчивалось длинным железным наконечником с крючком. Пилум бросался на расстоянии 7—10 м во вражеские щиты. Вонзенный пилум своей тяжестью оттягивал щит и лишал противника возможности прикрываться от ударов.'

In [9]:
sap_df = pd.read_json('./data/sap_generated/sap_train.json')
sap_df

,context,question,answer
0,Транзакция KS02 используется для изменения мас...,Для чего применяется транзакция KS02?,Для изменения мастер‑данных по МВЗ
1,Транзакция KSB1 позволяет просматривать деталь...,Какая транзакция позволяет видеть детальные пр...,KSB1
2,FB01 — транзакция для ввода бухгалтерских пров...,Какая транзакция позволяет вводить и корректир...,FB01
3,MB51 используется для формирования отчетов по ...,Какая транзакция позволяет анализировать прихо...,MB51
4,FS00 — транзакция для создания и изменения сче...,Для чего применяется транзакция FS00?,Для создания и изменения счетов главной книги
...,...,...,...
64,FB50 при вводе документов работает с таблицами...,Какие таблицы FB50 использует для сохранения д...,"BKPF, BSEG"
65,F‑02 использует таблицы BKPF и BSEG для хранен...,Из каких таблиц F‑02 получает данные для прово...,"BKPF, BSEG"
66,CO01 при создании производственного заказа сох...,Какие таблицы CO01 использует для сохранения п...,"AUFK, AFKO"
67,CO02 использует таблицы AUFK и AFKO для внесен...,Какие таблицы CO02 применяет для изменения про...,"AUFK, AFKO"
68,CO03 при просмотре заказа обращается к таблица...,Из каких таблиц CO03 получает данные для просм...,"AUFK, AFKO"

In [13]:
from datasets import load_dataset

dataset = load_dataset(
    "json",
    data_files={
        "train": "https://huggingface.co/datasets/RussianNLP/wikiomnia/resolve/main/dummy/wikiomnia_ruT5_filtered/wikiomnia_ruT5_filtered_train.json"
    }
)

print(dataset)

dummy/wikiomnia_ruT5_filtered/wikiomnia_(…):   0%|          | 0.00/4.28G [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['title', 'categories', 'summary', 'question', 'answer', 'batch_id'],
        num_rows: 2088027
    })
})

In [ ]:
df = dataset["train"].to_pandas()

In [34]:
df.head(20)

,title,categories,summary,question,answer,batch_id
0,Эд Генрих Бургундский,['Категория:Википедия:Статьи о государственных...,"Эд Генрих Великий (фр. Eudes-Henri le Grand, о...",Кто такой Эд Генрих Великий?,герцог Бургундии с 965,batch4
1,Эд Генрих Бургундский,['Категория:Википедия:Статьи о государственных...,"Эд Генрих Великий (фр. Eudes-Henri le Grand, о...",В каком году Эд Генрих Великий стал герцогом Б...,965,batch4
2,Ларри Барроуз,['Категория:Википедия:Статьи о фотографах без ...,Ларри Барроуз (англ. Larry Burrows; 29 мая 192...,Кто такой Ларри Барроуз?,английский фоторепортёр,batch4
3,Ларри Барроуз,['Категория:Википедия:Статьи о фотографах без ...,Ларри Барроуз (англ. Larry Burrows; 29 мая 192...,Кто такой Ларри Барроуз?,"английский фоторепортёр, получивший известност...",batch4
4,DOS extender,"['Категория:DOS', 'Категория:Википедия:Статьи ...",Расширитель DOS (также англ. DOS extender) — т...,Для чего нужна была работа в защищённом режиме...,для преодоления ограничения адресации в реальн...,batch4
5,DOS extender,"['Категория:DOS', 'Категория:Википедия:Статьи ...",Расширитель DOS (также англ. DOS extender) — т...,Для чего нужна работа в защищённом режиме проц...,для преодоления ограничения адресации в реальн...,batch4
6,Аббревиатуры библейских книг,['Категория:Википедия:Статьи без источников (т...,Единого списка сокращённых названий книг Библи...,Как обычно выглядит ссылка на текст из Библии?,следующим образом: Ин. 3:16,batch4
7,Аббревиатуры библейских книг,['Категория:Википедия:Статьи без источников (т...,Единого списка сокращённых названий книг Библи...,Как обычно выглядит ссылка на текст из Библии?,следующим образом: Ин. 3:16.,batch4
8,Тиопентал-натрий,"['Категория:Барбитураты', 'Категория:Википедия...",Тиопентал натрия (лат. Thiopentalum-natrium) —...,Что такое тиопентал натрия?,средство для неингаляционного наркоза ультрако...,batch4
9,Тиопентал-натрий,"['Категория:Барбитураты', 'Категория:Википедия...",Тиопентал натрия (лат. Thiopentalum-natrium) —...,Что такое Тиопентал натрия?,средство для неингаляционного наркоза ультрако...,batch4
10,Неразрешимость,['Категория:Википедия:Статьи c ненаписанными р...,Алгоритмическая разрешимость — свойство формал...,"Что является частным, но вместе с тем важнейши...",Вопрос о выводимости в формальной теории,batch4
11,Неразрешимость,['Категория:Википедия:Статьи c ненаписанными р...,Алгоритмическая разрешимость — свойство формал...,Чем является вопрос о выводимости в формальной...,"частным, но вместе с тем важнейшим случаем бол...",batch4
12,Заозерье (Руднянский район),['Категория:Википедия:Локальное значение кода ...,Заозерье — деревня в Смоленской области России...,В каком районе находится деревня Заозерье?,в Руднянском районе,batch4
13,Заозерье (Руднянский район),['Категория:Википедия:Локальное значение кода ...,Заозерье — деревня в Смоленской области России...,В каком районе расположена деревня Заозерье?,в Руднянском районе,batch4
14,Trevor Horn,"['Категория:T.A.T.u.', 'Категория:Википедия:Би...",Тревор Чарльз Хорн (англ. Trevor Charles Horn;...,Кто такой Тревор Чарльз Хорн?,"британский музыкальный продюсер, автор песен и...",batch4
15,Trevor Horn,"['Категория:T.A.T.u.', 'Категория:Википедия:Би...",Тревор Чарльз Хорн (англ. Trevor Charles Horn;...,"Как звали британского музыкального продюсера, ...",Тревор Чарльз Хорн,batch4
16,Университеты Нижнего Новгорода,['Категория:Высшие учебные заведения Нижнего Н...,"В Нижнем Новгороде находятся: 8 университетов,...",Сколько университетов находится в Нижнем Новго...,"8 университетов, 3 академии, консерватория и б...",batch4
17,Университеты Нижнего Новгорода,['Категория:Высшие учебные заведения Нижнего Н...,"В Нижнем Новгороде находятся: 8 университетов,...",Когда было открыто первое высшее учебное завед...,4(17) декабря 1911 года,batch4
18,Сарыколь (Костанайская область),['Категория:Википедия:Статьи без изображений (...,Сарыко́ль (каз. Сарыкөл) — посёлок городского ...,На какой линии находится станция Новоурицк?,Костанай—Кокшетау,batch4
19,Сарыколь (Костанайская область),['Категория:Википедия:Статьи без изображений (...,Сарыко́ль (каз. Сарыкөл) — посёлок городского ...,На какой линии находится Новоурицк?,Костанай—Кокшетау,batch4

In [35]:
import ast

unique_categories = set()

for row in dataset["train"]:
    cats = ast.literal_eval(row["categories"])  # превращаем строку в list
    for c in cats:
        unique_categories.add(c)

print("Всего уникальных категорий:", len(unique_categories))
print(list(unique_categories)[:20])

Всего уникальных категорий: 275738
['Категория:Переименованные улицы Минска', 'Категория:Пировский район', 'Категория:ФК «Ареццо»', 'Категория:Родившиеся в 390 году до н. э.', 'Категория:Википедия:Статьи без источников (страна: Ватикан)', 'Категория:Выпускники Томского государственного университета систем управления и радиоэлектроники', 'Категория:Euaesthetinae', 'Категория:Этапы WTCC в Германии', 'Категория:Незавершённые статьи о доспехах', 'Категория:Фильмы Дмитрия Михлеева', 'Категория:Банкиры Греции', 'Категория:Родившиеся в Чановском районе', 'Категория:Короткометражные телефильмы Рижской киностудии', 'Категория:Умершие в Новгород-Северском уезде', 'Категория:1933 год в СССР', 'Категория:Формула-1 в сезоне 2000', 'Категория:Казнённые в 1750-е годы', 'Категория:Притоки Мундыбаша', 'Категория:Умершие в Гельзенкирхене', 'Категория:Кодификаторы еврейского закона']

In [ ]:
# from datasets import load_dataset
# def qa1_to_text(example):
#     return {"text": example["вопрос"] + " " + example["ответ"]}

# stackoverflow_ds = load_dataset("zelkame/ru-stackoverflow-py", split="train")
# stackoverflow_ds = stackoverflow_ds.map(qa1_to_text, remove_columns=stackoverflow_ds.column_names)
# stackoverflow_ds

In [ ]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
import time

chrome_options = Options()
chrome_options.add_argument("--headless")  # Без окна
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=chrome_options
)

url = "https://help.sap.com/docs/SAP_S4HANA_ON-PREMISE/5e23dc8fe9be4fd496f8ab556667ea05/5cd170526837214fe10000000a445394.html?locale=ru-RU"
driver.get(url)
time.sleep(5)  # ждём, пока JS загрузит контент

# Получаем весь текст страницы
content = driver.find_element(By.TAG_NAME, "body").text

print(content[:10000])  # первые 1000 символов
driver.quit()

In [203]:
from docx import Document
import re


class DocxParser:

    def __init__(self, path: str):
        self.path = path
        self.chunks: list[str] = []

    # ---------- helpers ----------

    def _normalize(self, text: str) -> str:
        text = text.replace("\xa0", " ")
        text = re.sub(r"[ \t]+", " ", text)
        return text.strip()

    def _is_list_item(self, paragraph) -> bool:
        p = paragraph._p
        return p.pPr is not None and p.pPr.numPr is not None

    # ---------- main ----------

    def parse(self):
        doc = Document(self.path)
        current_chunk = []

        for paragraph in doc.paragraphs:
            raw_text = paragraph.text
            text = self._normalize(raw_text)

            if not text:
                continue

            # detect heading 1
            if paragraph.style.name.startswith("Heading 1"):
                if current_chunk:
                    self.chunks.append(
                        "<BOS>\n" +
                        "\n".join(current_chunk) +
                        "\n<EOS>"
                    )
                    current_chunk = []

                current_chunk.append(text + "\n")  # separating the header
                continue

            # restore list marker
            if self._is_list_item(paragraph):
                text = "- " + text

            current_chunk.append(text)

        # last chunk
        if current_chunk:
            self.chunks.append(
                "<BOS>\n" +
                "\n".join(current_chunk) +
                "\n<EOS>"
            )

        return self.chunks

In [206]:
# sap_df = pd.read_json('./data/sap_generated/sap_train.json')

parser = DocxParser("./data/sap_generated/SAPHelp_CO.docx")
samples = parser.parse()

print(len(samples))
print(samples[228])

231
<BOS>
Контрольный список для создания мест возникновения затрат

Вы создали контроллинговую единицу и присвоили ей одну или несколько балансовых единиц. Контроллинговой единице присвоен верхний узел стандартной иерархии (см. Ведение контроллинговых единиц в пользовательской настройке Общего контроллинга).
Если требуется использовать пользовательские виды мест возникновения затрат, необходимо определить их в пользовательской настройке Учета по местам возникновения затрат (CO-OM-CCA) (см. Ведение видов мест возникновения затрат).
В зависимости от видов МВЗ введены значения по умолчанию для планирования и проводки данных первичных и вторичных затрат или облиго.
Проверьте эти значения по умолчанию:
- Определена стандартная иерархия (см. Ведение стандартной иерархии в пользовательской настройке Учета по местам возникновения затрат).
- При необходимости проверьте существующие средства поиска (см. Определение средств поиска для мест возникновения затрат в пользовательской настройке Учета по местам возникновения затрат).
Создание мест возникновения затрат без активного учета по МВЗ
Даже если Учет по МВЗ (CO-OM-CCA) неактивен, можно создать места возникновения затрат как приблизительные записи для использования при проверке.
Это может быть полезно в следующих случаях:
- Финансы импортированы из SAP, но учет по ЦУ еще не активирован.
- Финансовый учет выполняется во внешней системе.
Этот метод позволяет указать МВЗ при проводке затрат по первичным видам затрат. Система проверяет, существует ли МВЗ при создании документа проводки. Можно создать данные из документов проводки, созданных системой SAP, для использования во внешних системах. МВЗ, указанное в документе проводки, может использоваться в качестве целевой контировки. Это обеспечивает возможность выполнения проводок только по МВЗ, которые фактически существуют.
В этой процедуре основные данные, сохраненные в базе данных, содержат только номер места возникновения затрат, контроллинговую единицу и период действия. Присвоение стандартной иерархии отсутствует. С помощью этого метода невозможно выполнить ведение основных данных, индикаторов, адресов или коммуникационных данных.
Планирование или проводка фактических затрат по МВЗ, созданным таким образом, невозможны.
Операции
Чтобы ввести приблизительные записи для этих МВЗ, выполните следующие действия:
- В управляющих индикаторах контроллинговой единицы установите для индикатора МВЗ значение 3 (компонент активен для проверок существования). Это можно сделать в руководстве по внедрению в разделе Контроллинг Контроллинг косвенных затрат > Учет по местам возникновения затрат > Ведение контроллинговой единицы.
- В меню Учета по МВЗ выберите Основные данные > МВЗ > Укрупненный ввод и создайте необходимые места возникновения затрат.
Для проводки плановых или фактических затрат по этим МВЗ необходимо ввести соответствующую информацию в функцию изменения основных данных. Необходимо дополнить основные данные и, при необходимости, дополнительные данные (например, индикаторы).
Проводки, созданные в Финансах, также можно перенести в учет по МВЗ. Для получения дополнительной информации см. руководство по внедрению в разделе Контроллинг > Общий контроллинг > Подготовка продуктивного запуска > Последующая проводка > Провести последующие операции из бухгалтерских документов.
<EOS>

In [42]:
import pdfplumber

texts = []
with pdfplumber.open("C:/Users/Akulich_SA/Downloads/fc_101_webHTML5_user_ru.pdf") as pdf:
    for page in pdf.pages:
        texts.append(page.extract_text())

full_text = "\n".join([t for t in texts if t])

In [43]:
full_text

'Руководство пользователя\nPUBLIC (ОБЩЕДОСТУПНО)\nSAP Financial Consolidation\nВерсия документа: 10.1 Support Package 09 – 2024-05-11\nРуководство пользователя веб-приложения\nHTML5 SAP Financial Consolidation\n.ынещищаз\nаварп\nесВ\n.4202\n,PAS\nяинапмок\nяаннаворилиффа\nили\nES\nPAS\n©\nTHE BEST RUN\nСодержание\n1 SAP Financial Consolidation. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .10\n2 Основные функции пользователя. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 11\n2.1 Вход в SAP Financial Consolidation. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .11\n2.2 Выход из SAP Financial Consolidation. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .11\n2.3 Возврат на домашнюю страницу. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .12\n2.4 Доступ к Web Assistant. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .12\n2.5 Настройка предпочтений пользователя. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .12\nИзменение пароля. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 13\nВыбор языков отображения. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 13\n2.6 Просмотр личных данных. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 14\n2.7 Действия над списками. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .14\nФильтрация в списках. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .15\nПоиск элементов. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 15\nСортировка объектов в порядке возрастания или убывания. . . . . . . . . . . . . . . . . . . . . . . . . 16\nОтображение, изменение порядка, сортировка и изменение размера столбцов. . . . . . . . . . 16\nФиксация столбцов в списке. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .17\nОтображение числа элементов и разбиение на страницы. . . . . . . . . . . . . . . . . . . . . . . . . . .18\nВыбор элементов и отображение только моего выбора. . . . . . . . . . . . . . . . . . . . . . . . . . . . .18\nПросмотр результатов с ошибками после обработки действия. . . . . . . . . . . . . . . . . . . . . . .19\n2.8 Выбор элементов измерений. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .19\nМетоды выбора. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 19\nВвод элементов измерения. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 20\nУдаление элементов измерения. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .21\n2.9 Верхний колонтитул страницы редактора. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 21\n2.10 Ввод или вставка сумм. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 23\n2.11 Закрытие элемента. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .23\n2.12 Ввод комментария и управление вложениями файлов. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 23\nВвод комментария. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .24\nДобавление вложенных файлов. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 24\nЗагрузка вложенного файла. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 25\nУдаление вложенных файлов. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 25\n2.13 Печать элементов. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .26\nСпециальные параметры печати для форм и отчетов. . . . . . . . . . . . . . . . . . . . . . . . . . . . . .27\n2.14 Настройка страницы входа в систему и начальной страницы для всех пользователей\nкомпании. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 27\nНастройка фоновых изображений страницы входа и домашней страницы. . . . . . . . . . . . . .28\nPUBLIC Руководство пользователя веб-приложения HTML5 SAP Financial Consolidation\n2 ОБЩЕДОСТУПНО Содержание\nОпределение и отображение сообщений на странице входа в систему. . . . . . . . . . . . . . . . 28\nОпределение и отображение пользовательского содержимого на странице входа в\nсистему. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .30\nОпределение сообщений домашней страницы. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .32\nОпределение пользовательских плиток домашней страницы. . . . . . . . . . . . . . . . . . . . . . . .33\nИспользование надлежащих кодов языков для перевода. . . . . . . . . . . . . . . . . . . . . . . . . . .37\nИзменение значков. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 38\n3 Домашняя страница. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .41\n3.1 Отображение плиток на главной странице. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 41\n3.2 Моя недавняя работа. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 42\nЧтение информации плиток последних объектов. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .42\nПеремещение между плитками последних объектов. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 42\nУдаление плиток недавних объектов. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 43\n3.3 Открытие плиток на новой вкладке или в новом окне. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 43\n4 Пакеты. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 44\n4.1 Статусы и допустимость пакета. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 44\n4.2 Проверки и уровни проверок. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .49\n4.3 Рабочий процесс. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 50\n4.4 Публикация пакета. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .50\n4.5 Групповое сообщение и комментарий пакета. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 51\n4.6 Блокировка и защита пакетов. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 51\n4.7 Однопользовательский и многопользовательский режимы. . . . . . . . . . . . . . . . . . . . . . . . . . . .52\n4.8 Список пакетов. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .52\nОткрытие пакета. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 54\nПубликация нескольких пакетов. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 55\nИнтеграция нескольких пакетов. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .56\nОбнуление нескольких пакетов. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 57\nУтверждение нескольких пакетов в рабочем процессе. . . . . . . . . . . . . . . . . . . . . . . . . . . . .58\nОтклонение пакета в рабочем процессе. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .58\nЗащита или снятие защиты с нескольких пакетов. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 59\nРазблокирование нескольких пакетов. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 59\nЭкспорт данных из пакетов в файл. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 60\n4.9 Заголовок страницы пакета. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .61\n4.10 Просмотр группового сообщения. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .62\n4.11 Ввод данных в формы пакетов. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 63\nОткрытие формы. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .63\nСимволы в ячейках формы ввода данных. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .65\nНастройка отображения формы. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 65\nВставка элементов в форму ввода данных. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .68\nУдаление элементов из формы ввода данных. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 69\nРуководство пользователя веб-приложения HTML5 SAP Financial Consolidation PUBLIC\nСодержание ОБЩЕДОСТУПНО 3\nОбращение к инструкциям по вводу данных. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .70\nКопирование данных. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 71\nОтмена и повтор ввода данных. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .73\nВставка/просмотр комментария для суммы. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .74\nПоиск текста или суммы в форме. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .74\nПросмотр сведений о данных. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .75\nДетализация до источника на странице SAP Financial Information Management. . . . . . . . . . .76\nПеремещение между листами формы. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 77\nНавигация по формам с использованием связанных форм. . . . . . . . . . . . . . . . . . . . . . . . . .77\nНавигация по формам с использованием истории. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 78\nОбновление формы вручную. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 78\n4.12 Ввод и просмотр корректировок в пакете. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 79\nВвод/просмотр корректировок форм. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 79\nПросмотр разных бухгалтерских книг и проводок. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 80\nВвод корректировок проводок. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 81\nСоздание корректировок автоматических проводок с использованием правил пакета\n. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 85\n4.13 Импорт данных из файла, таблицы или пакета в пакет. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 86\nОпределение источника данных. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 86\nОпределение параметров импорта. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .88\nОпределение действий для выполнения после импорта. . . . . . . . . . . . . . . . . . . . . . . . . . . .89\nВыполнение импорта. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .89\nАнализ отклонений импорта. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 90\n4.14 Выполнение проверок данных пакета и просмотр результатов. . . . . . . . . . . . . . . . . . . . . . . . . 91\nВыполнение проверок в пакете. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 92\nВыполнение проверок из виджета проверки форм. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .93\n4.15 Экспорт данных в файл из пакета. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .94\n4.16 Отображение пользователей, подключенных к пакету (многопользовательский режим)\n. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .94\n4.17 Утверждение пакета в рабочем процессе. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 95\n4.18 Отклонение пакета в рабочем процессе. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 96\n4.19 Выполнение расчетов для предварительной загрузки данных. . . . . . . . . . . . . . . . . . . . . . . . . .96\n4.20 Выполнение правил пакетов. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .97\n4.21 Обнуление пакета. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .98\n4.22 Проверка пакета. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .98\n4.23 Публикация пакета. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .100\n4.24 Сохранение пакета. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 101\n4.25 Закрытие пакета. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 101\n5 Импорт пакетов из файла или таблицы. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 103\n5.1 Статусы импорта пакетов. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 103\n5.2 Определение источника данных. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 103\nPUBLIC Руководство пользователя веб-приложения HTML5 SAP Financial Consolidation\n4 ОБЩЕДОСТУПНО Содержание\n5.3 Выбор пакетов. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .105\n5.4 Определение параметров импорта. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 106\n5.5 Определение действий для выполнения после импорта. . . . . . . . . . . . . . . . . . . . . . . . . . . . . .107\n5.6 Выполнение импорта. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .107\n5.7 Анализ отклонений импорта. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 108\n5.8 Публикация пакетов после импорта нескольких пакетов в многопользовательском режиме\n. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .109\n5.9 Выполнение правил пакетов после импорта нескольких пакетов в многопользовательском\nрежиме. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 110\n6 Импорт пакетов из источников SAP S/4HANA. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .112\n6.1 Определение параметров импорта пакетов из источников S/4HANA. . . . . . . . . . . . . . . . . . . . 112\n6.2 Анализ результата импорта пакета для источников S/4HANA. . . . . . . . . . . . . . . . . . . . . . . . . .114\n7 S/4 HANA Data Monitor. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 116\n7.1 Фильтрация информации страницы. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .116\n7.2 Обновление информации страницы. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .116\n7.3 Определение Data Link. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .117\n7.4 Журнал преобразования. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 117\nОбработка журналов преобразования. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .117\nПереопределение исходных столбцов журнала преобразования. . . . . . . . . . . . . . . . . . . . .118\nСтатус журнала преобразования. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .118\n7.5 Доступны новые данные S/4HANA. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 119\n7.6 Дата импорта данных. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 120\n8 Определения Data Link. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 121\n8.1 Страница определений Data Link. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 121\nОткрытие определений Data Link. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 122\nДублирование определений Data Link. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .122\nУдаление определений Data Link. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 123\n8.2 Создание определений Data Link. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .124\nСтатусы определений Data Link. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .125\nЗаголовок редактора определений Data Link. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .127\nОпределение настроек. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .128\nОпределение источника. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .128\nОпределение мэппинга. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 140\nОбновление фиксированных значений. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .155\nДобавление комментария. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .157\nДублирование определений Data Link в редакторе. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 158\nРазвертывание определений Data Link S/4HANA. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .159\nОткрытие задания Data Link или импорт пакета. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 160\n9 Задание Data Link. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 162\nРуководство пользователя веб-при

In [3]:
def qa2_to_text(example):
    question = example["question"]
    # объединяем все ответы в одну строку через пробел
    answer = " ".join(example["human_answers"]) if isinstance(example["human_answers"], list) else str(example["human_answers"])
    return {"text": question + " " + answer}
    
qa_ds = load_dataset("d0rj/HC3-ru", split="train")
qa_ds = qa_ds.map(qa2_to_text, remove_columns=qa_ds.column_names)
qa_ds

Dataset({
    features: ['text'],
    num_rows: 24322
})

In [ ]:
# from datasets import load_dataset

# poems_ds = load_dataset("csv", data_files="./data/poems.csv")
# poems_ds

In [5]:
from datasets import concatenate_datasets

# оставляем только текст
ds1_text = wiki.remove_columns([c for c in wiki.column_names if c != "text"])
ds2_text = stackoverflow_ds.remove_columns([c for c in stackoverflow_ds.column_names if c != "text"])
ds3_text = qa_ds.remove_columns([c for c in qa_ds.column_names if c != "text"])
ds4_text = poems_ds["train"].remove_columns([c for c in poems_ds["train"].column_names if c != "text"])

combined_ds = concatenate_datasets([ds1_text, ds2_text, ds3_text, ds4_text])
combined_ds

Dataset({
    features: ['text'],
    num_rows: 2003818
})

In [6]:
import re
from datasets import Dataset

class DataCleaner:
    def __init__(self, min_length=500):
        self.min_length = min_length
        self.citation_pattern = re.compile(r"\[\d+\]")
        self.parentheses_pattern = re.compile(r"\([^()]*\)")
        self.space_before_punct = re.compile(r"\s+([,.;:])")
        self.double_symbols = re.compile(r"([.,/:;!~$%^&*#+-=]){2,}")

    
    def clean_text(self, text: str) -> str:
        if not text:
            return ""

        # Remove citation markers like [1], [23]
        text = self.citation_pattern.sub("", text)

        # Remove nested parentheses iteratively
        while self.parentheses_pattern.search(text):
            text = self.parentheses_pattern.sub("", text)

        # replace multiple symbols with one
        text = self.double_symbols.sub(r"\1", text)

        # Remove space before punctuation: " ," -> ","
        text = self.space_before_punct.sub(r"\1", text)

        text = re.sub(r'\xad', '', text)

        # Normalize whitespace
        text = " ".join(text.split())
        return text
    

    def is_valid(self, text: str) -> bool:
        if len(text) < self.min_length:
            return False
        
        # Optional: filter pages with too many non-letter symbols
        letters_ratio = sum(c.isalpha() for c in text) / max(len(text), 1)
        if letters_ratio < 0.6:
            return False

        return True
    

    def process_dataset(self, dataset: Dataset) -> Dataset:
        def process(example):
            text = self.clean_text(example["text"])
            if self.is_valid(text):
                return {"text": text}
            else:
                return {"text": None}

        dataset = dataset.map(process)
        dataset = dataset.filter(lambda x: x["text"] is not None)
        return dataset

In [7]:
cleaner = DataCleaner(min_length=200)
clean_ds = cleaner.process_dataset(combined_ds)
clean_ds

Dataset({
    features: ['text'],
    num_rows: 1915217
})

In [8]:
for i in range(1660000, 1660015):
    print(clean_ds[i]["text"])

Глубокая — деревня в Юргамышском районе Курганской области. Входит в состав Скоблинского сельсовета. История До 7 года в составе Таловской волости Курганского уезда Тобольской губернии. По данным на 6 год состояла из 5 хозяйств. В административном отношении входила в состав Таловского сельсовета Юргамышского района Курганского округа Уральской области. Население По данным переписи 6 года в деревне проживало 4 человека, в том числе: русские составляли 0 % населения. Примечания Населённые пункты Юргамышского района
Таловка — село в Юргамышском районе Курганской области. Входит в состав Скоблинского сельсовета. История До 7 года центр Таловской волости Курганского уезда Тобольской губернии. По данным на 6 год село Таловское состояло из 8 хозяйств. В административном отношении являлось центром Таловского сельсовета Юргамышского района Курганского округа Уральской области. Население По данным переписи 6 года в селе проживало 9 человек, в том числе: русские составляли 0 % населения. Примечания Населённые пункты Юргамышского района
Скоблино — село в Юргамышском районе Курганской области. Административный центр Скоблинского сельсовета. История До 7 года в составе Таловской волости Курганского уезда Тобольской губернии. По данным на 6 год состояло из 1 хозяйства. В административном отношении являлось центром Скоблинского сельсовета Юргамышского района Курганского округа Уральской области. Население По данным переписи 6 года в селе проживало 3 человека, в том числе: русские составляли 0 % населения. Примечания Населённые пункты Юргамышского района
Камаган — деревня в Юргамышском районе Курганской области. Входит в состав Скоблинского сельсовета. История До 7 года в составе Таловской волости Курганского уезда Тобольской губернии. По данным на 6 год состояла из 4 хозяйств. В административном отношении входила в состав Скоблинского сельсовета Юргамышского района Курганского округа Уральской области. Население По данным переписи 6 года в деревне проживало 6 человек, в том числе: русские составляли 0 % населения. Примечания Населённые пункты Юргамышского района
Патракова — деревня в Юргамышском районе Курганской области. Входит в состав Чинеевского сельсовета. История До 7 года в составе Чинеевской волости Курганского уезда Тобольской губернии. По данным на 6 год состояла из 2 хозяйств. В административном отношении входила в состав Чинеевского сельсовета Юргамышского района Курганского округа Уральской области. Население По данным переписи 6 года в деревне проживало 7 человек, в том числе: русские составляли 0 % населения. Примечания Населённые пункты Юргамышского района
Пестерева — деревня в Юргамышском районе Курганской области. Входит в состав Чинеевского сельсовета. История До 7 года в составе Кисляковской волости Курганского уезда Тобольской губернии. По данным на 6 год деревня Большая Белая состояла из 9 хозяйств. В административном отношении входила в состав Чинеевского сельсовета Юргамышского района Курганского округа Уральской области. Население По данным переписи 6 года в деревне проживало 3 человека, в том числе: русские составляли 0 % населения. Примечания Населённые пункты Юргамышского района
Центр гимнастики Ариакэ — это временное спортивное сооружение, расположенное на юге японской столицы Токио, точнее в квартале Ариакэ района Кото в Токио. Центр построен к началу Олимпиады. В этом спортивном сооружении прошли соревнования по спортивной и художественной гимнастике и прыжкам на батуте, а также состязания в бочче паралимпийских игр. После турнира арена будет работать как выставочный зал около 0 лет. Строительство Дизайнерский проект был осуществлён японским архитектурно-дизайнерским бюро Nikken Sekkei Co, Ltd. Строительство объекта началось в 7 году и завершено 5 октября 9 г. Здание имеет 3 надземных этажа, площадь застройки 1 1 квадратный метр и общую площадь 9 4 квадратных метра. В зале около 2 0 мест. Спортивные соревнования 9 — -Й ЧЕМПИОНАТ МИРА ПО ПРЫЖКАМ НА БАТУТЕ Примечания Ссылки Спортивные сооружения летних Олимпийских игр 0 года Спортивные сооружения Токио Кото
Ceremony — третий студийный альбом японской рок-группы King Gnu, выпущенный 5 января 0 года на лейбле. Об альбоме Запись была издана в двух форматах: на CD и в связке CD и Blu-ray. 2 декабря 0 года Ceremony вместе с предыдущими альбомами группы Tokyo Rendez-Vous и Sympa вышел на виниле. Пластинка заняла -е место в еженедельном чарте Oricon, за первую неделю её продажи составили 8 0 физических и 0 0 цифровых копий. Альбом пребывал 8 недель в десятке чарта Billboard Japan Hot Albums Chart, включая четыре недели на его вершине. По всему миру продажи записи достигли одного миллиона экземпляров, таким образом Ceremony вошёл число самых продаваемых альбомов 0 года. Ceremony стал одним из нескольких альбомов, отмеченных наградами на в 1 году. Также он был признан одним из пяти лучших альбомов во время церемонии Japan Gold Disc Awards. Список композиций Автор всех композиций — Дайки Цунэта. Чарты и сертификация Еженедельные чарты Годовые итоговые чарты Сертификации Примечания Альбомы Японии Альбомы на японском языке
Кайл Соллер — американский актёр театра, кинематографа и телевидения. Обладатель Премии Лоренса Оливье и трёхкратный обладатель премии Evening Standard. Ранние годы Кайл Соллер родился в Бриджпорте, штат Коннектикут, и вырос в Александрии. Он посещал Колледж Вильгельма и Марии, где изучал историю искусств. На третьем курсе он провёл семестр по обмену в Королевской академии драматического искусства в Лондоне, после чего ему было предложено остаться и продолжить обучение. Соллер перевёлся в Академию, где и закончил своё образование. Театральная карьера Соллер окончил RADA в 8 году, после чего активно играл на британской сцене. Прорыв в карьере наступил в 1 году, когда за 8 месяцев он сыграл роль Джима в постановке «Стеклянного зверинца», Хлестакова в адаптации «Ревизора» и в получившей одобрение критиков новой пьесе «The Faith Machine» в театре Ройал-Корт. Эти три работы принесли ему премию газеты Evening Standard в номинации «Выдающийся дебют». В 2 году в театре «Аполло» Соллер играет роль Эдмунда Тайрона в новой постановке пьесы Юджина О'Нила «Долгий день уходит в ночь», где его партнёрами были Дэвид Суше и Лори Меткалф. Позже в Нью-Йорке в театре American Airlines играет Кристиана в адаптации «Сирано де Бержерака». В 3 году в Королевском национальном театре в пьесе «Эдвард II» исполнил роль Пирса Гавестона, в 6 году — Георга Тесмана в «Гедде Габлер». В 8 году в театре Янг Вик Стивен Долдри поставил пьесу Мэтью Лореза «Наследство». В двучастной семичасовой адаптации романа Э.М.Фостера «Говардс Энд» Кайл Соллер сыграл главную роль Эрика Гласса — прообраз главной героини романа Маргарет Шлегель. За своё исполнение актёр получил Премию Лоренса Оливье, премию газеты Evening Standard и премию Кружка театральных критиков. Актёр повторил свою роль при переносе пьесы в более крупный театр Ноэла Кауарда в Вест-Энде и после трансфера пьесы в театр Этель Бэрримор на Бродвее. Личная жизнь В 0 году Соллер женился на актрисе Фиби Фокс, с которой познакомился в Королевской академии драматического искусства. Фильмография Примечания Ссылки Выпускники Королевской академии драматического искусства Киноактёры США
Чинеевский Участок — посёлок в Юргамышском районе Курганской области. Входит в состав Чинеевского сельсовета. История До 7 года в составе Чинеевской волости Курганского уезда Тобольской губернии. По данным на 6 год деревня Чинеевская состояла из 6 хозяйств. В административном отношении входила в состав Чинеевского сельсовета Юргамышского района Курганского округа Уральской области. Население По данным переписи 6 года в деревне проживало 9 человек, в том числе: русские составляли 9 % населения. Примечания Населённые пункты Юргамышского района
Олимпийская сборная Франции по футболу — с 2 года является отдельной командой, собираемой для участия в Олимпийских играх в дисциплине «Футбол». С 2 года изменились правила участия в Олимпийских играх, вследствие чего участие сборной зависит от результатов игры молодежной сборной. В заявку сборной на Олимпийские игры могут включаться игроки не старше 3 лет, за исключением трёх футболистов, которые могут быть старше этого возраста. История Статистика выступлений Текущий состав сборной Ниже перечислены игроки, которые были включены в заявку сборной Франции на Олимпийские игры 0 в Японии. По правилам в заявку могут быть включены 3 игрока старше 3 лет. Статистика игр Примечания Ссылки Футбол во Франции Франция на Олимпийских играх Франция Сборная Франции по футболу
Чинеево — село в Юргамышском районе Курганской области. Административный центр Чинеевского сельсовета. История До 7 года центр Чинеевской волости Курганского уезда Тобольской губернии. По данным на 6 год состояло из 5 хозяйств. В административном отношении являлось центром Чинеевского сельсовета Юргамышского района Курганского округа Уральской области. Население По данным переписи 6 года в деревне проживало 0 человек, в том числе: русские составляли 9 % населения. Примечания Населённые пункты Юргамышского района
Новая Заво́рина — деревня в Юргамышском районе Курганской области. Входит в состав Чинеевского сельсовета. История До 7 года в составе Чинеевской волости Курганского уезда Тобольской губернии. По данным на 6 год состояла из 0 хозяйств. В административном отношении входила в состав Медвежьевского сельсовета Юргамышского района Курганского округа Уральской области. Население По данным переписи 6 года в деревне проживало 2 человека, в том числе: русские составляли 0 % населения. Примечания Населённые пункты Юргамышского района
Зырянка — посёлок в Юргамышском районе Курганской области. Входит в состав Чинеевского сельсовета. История До 7 года в составе Чинеевской волости Курганского уезда Тобольской губернии. По данным на 6 год состоял из 8 хозяйств. В административном отношении входил в состав Медвежьевского сельсовета Юргамышского района Курганского округа Уральской области. Население По данным переписи 6 года в посёлке проживало 9 человек, в том числе: русские составляли 9 % населения. Примечания Населённые пункты Юргамышского района
Тацуо Хори — японский писатель, поэт, переводчик эпохи Сёва. Ранние годы Хори родился близ Токио в районе Kōjimachi и окончил Токийский императорский университет. Ещё во время учебы в колледже стал участником молодёжных общественных организаций, где завёл знакомство с политически настроенными авторами и критиками, такими как Накано Шигехару и Кубота Цуруджиро. В 6 они основали литературный журнал Rōba, в дальнейшем спонсируемый поэтом Муро Саисэи, в котором были опубликованы переводы многих французских произведений, написанные самим Тацуо. Он считал себя учеником Рюноскэ Акутагавы, но, с точки зрения его друзей Нагая Тацуо и Кобаяси Хидео, ранние работы поэта тяготеют к пролетарскому литературному движению. Более поздние труды Хори отражают движение в сторону модернизма. Стоит отметить, что стиль Тацуо также формировался под влиянием популярной тогда в Японии французской школы, в частности работы Реймонда Радиге, Райнера Мария Рильке, Франсуа Мориака и Марселя Пруста. Литературная карьера Тацуо Хори написал целый ряд повестей и стихотворений, действие которых происходит в местах, наполненных особой атмосферой, например, таких как горный санаторий в префектуре Нагано, и характеризуется темой смерти, в которой была отражена его собственная непрекращающаяся борьба с туберкулезом. Часто бессюжетный и импрессионистический, его стиль был высоко оценен Кавабатой Ясунари. В 0 году Хори впервые получил признание общества благодаря рассказу «Святое семейство», написанному под впечатлением смерти Акутагавы, образ которого был воплощён в погибшем персонаже Куки. Одним из известнейших произведений Хори является цикл «Яматодзи», небольшой сентиментальный сборник поэтических эссе о Наре и её исторических местах. Затем последовал трагический роман «Адасино», действие которого происходит в период Нара. Именно эти подробные описания, исполненные прекрасными сравнениями и символами, во многом популяризированные властями города для привлечения туристов, принесли поэту славу. Был одним из создателей и участников поэтического журнала «Лошадь». Название журнала было предложено Тацуо Хори, а название и обложка были отрисованы личным врачом Рюноскэ Акутагавы Рюносукэ и поэтом хайку Симодзимой Сорайей. Придерживаясь традиций классической европейской литературы, а также публикуя революционные произведения и стихотворения, создаваемые в стиле японской литературы -го века, журнал занимал важное историческое положение среди других журналов додзинси с конца эпохи Тайсё до раннего периода Сёва. Память В городе Каруидзава префектуры Нагано, где Хори останавливался во время обострения болезни, в его честь был основан Мемориальный музей Хори Тацуо. Могила писателя находится на Тама Рэйэн, кладбище на окраине Токио. Роман «Ветер поднялся», название которого заимствовано из поэмы французского поэта Поля Валери «Кладбище у моря», вдохновил режиссёра Хаяо Миядзаки на создание одноименного аниме со схожими фрагментами из книги. Роман «Ветер поднялся» автобиографичен. Сюжет повествует о любви молодого писателя к больной туберкулезом девушке-художнице Сэцуко. Прототипами главных героев романа послужили сам писатель и Аяко Яно, с которой Хори познакомился летом 3 года. Он «встретил невинную, красивую девочку, такую, как подсолнечник в Каруидзаве и сердце, которое страдало — и исцелилось». Об этом Тацуо пишет в 3 году в свое более раннем произведении — «Красивая деревня». В произведении он продолжает ту же тему, но уже при более трагических обстоятельствах: у его невесты туберкулез. Лечение этой болезни было невозможным, и только чистый горный воздух и крепкий молодой организм, по мнению врачей, могли противостоять недугу в то время. Аяко Яно находится в санатории в предгорьях на плато Фудзими, а он — рядом с ней. В свой фильм Хаяо Миядзаки включил эпизоды, где Дзиро Хорикоси встречает молодую девушку, рисующую пейзажи, её болезнь и лечение в удаленном от Токио санатории. Основные работы «Святое семейство» 2 год «Красивая деревня» 3 год «Поднялся ветер» 6—7 годы «Дневники», 7 год «Наоко» 1 год «Арано» 1 год «Детство» 2 год Примечания Переводчики Японии Поэты Японии

#### Tokenizer

In [1]:
from pathlib import Path
from tokenizers import ByteLevelBPETokenizer, Tokenizer
from tokenizers.processors import TemplateProcessing
from tqdm import tqdm


class BPETokenizer:
    def __init__(self, save_dir: str, vocab_size: int = 32000, min_frequency: int = 2):
        self.save_dir = Path(save_dir)
        self.save_dir.mkdir(parents=True, exist_ok=True)
        self.tokenizer_path = self.save_dir / "tokenizer.json"
        self.vocab_size = vocab_size
        self.min_frequency = min_frequency
        

    def train(self, dataset):
        tokenizer = ByteLevelBPETokenizer()

        def text_iterator():
            for example in tqdm(dataset, total=len(dataset), desc="Training BPE"):
                yield example["text"]

        tokenizer.train_from_iterator(
            text_iterator(),
            vocab_size=self.vocab_size,
            min_frequency=self.min_frequency,
            special_tokens=["<PAD>", "<BOS>", "<EOS>"],
        )

        # Add post-processor  
        tokenizer.post_processor = TemplateProcessing(
            single="<BOS> $A <EOS>",
            special_tokens=[
                ("<BOS>", tokenizer.token_to_id("<BOS>")),
                ("<EOS>", tokenizer.token_to_id("<EOS>")),
            ],
        )

        tokenizer.save(str(self.tokenizer_path))
        print("Tokenizer saved!")

        return tokenizer

    def from_file(self):
        if not self.tokenizer_path.exists():
            raise FileNotFoundError(f"{self.tokenizer_path} not found")

        tokenizer = Tokenizer.from_file(str(self.tokenizer_path))
        return tokenizer

#### Training tokenizer

In [2]:
tokenizer = BPETokenizer(save_dir='./tokenizers/bpe_tokenizer_v3', vocab_size=32000, min_frequency=2)
# bpe_tokenizer = tokenizer.train(clean_ds)

Download tokenizer from file

In [3]:
bpe_tokenizer = tokenizer.from_file()

print(bpe_tokenizer.get_vocab_size())
encoded = bpe_tokenizer.encode("Привет мир")
print(encoded.ids)
print(encoded.tokens)

32000
[1, 22984, 309, 2245, 2]
['<BOS>', 'ÐŁÑĢÐ¸Ð²', 'ÐµÑĤ', 'ĠÐ¼Ð¸ÑĢ', '<EOS>']

In [38]:
txt = 'Задача на системы счисления, код выдаёт ошибку.'
bpe_tokenizer.encode(txt).ids

[1, 3096, 16551, 314, 2612, 283, 2264, 775, 14, 5310, 6026, 941, 23145, 16, 2]

In [7]:
# import torch
# from tokenizers.processors import TemplateProcessing

# class LMDataset(torch.utils.data.Dataset):
#     def __init__(self, tokenizer, corpus, block_size=512):
#         self.block_size = block_size
#         self.tokenizer = tokenizer

#         # Configure post-processor
#         tokenizer.post_processor = TemplateProcessing(
#             single="<BOS> $A <EOS>",
#             special_tokens=[
#                 ("<BOS>", tokenizer.token_to_id("<BOS>")),
#                 ("<EOS>", tokenizer.token_to_id("<EOS>")),
#             ],
#         )

#         # Tokenize and concatenate all tokens
#         all_ids = []
#         for article in corpus:
#             ids = tokenizer.encode(article["text"] ).ids
#             all_ids.extend(ids)

#         # Chunk into blocks
#         self.chunks = [
#             all_ids[i:i+block_size] for i in range(0, len(all_ids) - block_size, block_size)
#         ]

#     def __len__(self):
#         return len(self.chunks)

#     def __getitem__(self, idx):
#         chunk = torch.tensor(self.chunks[idx], dtype=torch.long)
#         return {"input_ids": chunk, "labels": chunk.clone()}

In [ ]:
# from torch.utils.data import DataLoader

# dataset = LMDataset(bpe_tokenizer, clean_ds, block_size=512)
# loader = DataLoader(dataset, batch_size=8, shuffle=True)

In [ ]:
import numpy as np
from tqdm import tqdm

def build_bin(tokenizer, dataset, output_path, batch_size=10000, dtype=np.uint16):
    with open(output_path, "wb") as f:
        for i in tqdm(range(0, len(dataset), batch_size)):
            batch = dataset[i:i+batch_size]['text']  
            encoded_batch = tokenizer.encode_batch(batch)

            all_ids = []
            for row in encoded_batch:
                all_ids.extend(row.ids)

            np.array(all_ids, dtype=dtype).tofile(f)

build_bin(bpe_tokenizer, clean_ds, './data/embed_corpus')

In [5]:
import os
import torch
import numpy as np

class LMDataset(torch.utils.data.Dataset):
    """ 
    Dataset only provides token sequences.
    The autoregressive shift is applied inside the model during loss computation, 
    keeping data loading independent from training objective.
    """
    def __init__(self, path, block_size=512, dtype=np.uint16):
        self.block_size = block_size
        file_size = os.path.getsize(path)
        self.total_tokens = file_size // np.dtype(dtype).itemsize
        self.data = np.memmap(path, dtype=dtype, mode="r")

    def __len__(self):
        return self.total_tokens // self.block_size

    def __getitem__(self, idx):
        start = idx * self.block_size
        end = start + self.block_size

        chunk = torch.from_numpy(self.data[start:end].astype(np.int64))

        return {"input_ids": chunk}

In [6]:
gen_dataset = LMDataset(
    path='./data/embed_corpus_train',
    block_size=1024,
    dtype=np.uint16
)
print(len(gen_dataset))
print(gen_dataset[0]["input_ids"].shape)

886894
torch.Size([1024])

In [7]:
from torch.utils.data import DataLoader

gen_loader = DataLoader(
    gen_dataset,
    batch_size=4,
    shuffle=True,
    num_workers=0,
    pin_memory=False
)

In [8]:
batch = next(iter(gen_loader))

print(batch["input_ids"].shape)
batch["input_ids"][0]

torch.Size([4, 1024])

tensor([2277, 4849, 3440,  ...,  358, 1813, 3819])

#### Rotary Position Embedding (RoPE)

In [9]:
import torch
import torch.nn as nn

class RotaryEmbedding(nn.Module):
    def __init__(self, dim, base=10000):
        super().__init__()
        self.dim = dim
        self.base = base

        inv_freq = 1.0 / (base ** (torch.arange(0, dim, 2).float() / dim))
        self.register_buffer("inv_freq", inv_freq)

        self._seq_len = None
        self._cos = None
        self._sin = None

    def forward(self, seq_len, dtype):
        device = self.inv_freq.device
        if (
            seq_len != self._seq_len
            or self._cos.device != device
            or self._cos.dtype != dtype
        ):
            positions = torch.arange(seq_len, device=device).float()
            theta = torch.outer(positions, self.inv_freq)
            self._cos = theta.cos().to(dtype).unsqueeze(0).unsqueeze(0)
            self._sin = theta.sin().to(dtype).unsqueeze(0).unsqueeze(0)
            self._seq_len = seq_len

        return self._cos, self._sin
    

def apply_rope(q, k, cos, sin):
    # q, k: (B, H, T, D)
    # cos, sin: (1, 1, T, D/2)

    # Чётные и нечётные координаты (q1, q2) -> (x0​,x1​), (x2​,x3​), ...
    q1 = q[..., ::2]   # q1 = (B, H, T, D/2),  D/2 -> [ x0, x2, x4, ... ] 
    q2 = q[..., 1::2]  # q1 = (B, H, T, D/2),  D/2 -> [ x1, x3, x5, ... ]
    k1 = k[..., ::2]   # k1 = (B, H, T, D/2),  D/2 -> [ x0, x2, x4, ... ] 
    k2 = k[..., 1::2]  # k1 = (B, H, T, D/2),  D/2 -> [ x1, x3, x5, ... ]

    q_rot = torch.empty_like(q)
    k_rot = torch.empty_like(k)

    # Rotation q and k, broadcast (1,1,T,D/2)→(B,H,T,D/2)
    q_rot[..., ::2] = q1 * cos - q2 * sin
    q_rot[..., 1::2] = q1 * sin + q2 * cos

    k_rot[..., ::2] = k1 * cos - k2 * sin
    k_rot[..., 1::2] = k1 * sin + k2 * cos

    return q_rot, k_rot

#### Multi Head Self Attention

In [10]:
import torch
import torch.nn as nn
import math

class MultiHeadSelfAttention(nn.Module):
    def __init__(self, d_model, n_heads, max_seq_len, dropout_rate=0.1):
        super().__init__()
        self.n_heads = n_heads
        
        assert d_model % n_heads == 0, "d_model must be divisible by n_heads"
        self.head_dim = d_model // n_heads

        # Positional embedding RoPE
        self.rope = RotaryEmbedding(self.head_dim)

        # Attantion layer
        self.qkv = nn.Linear(d_model, 3 * d_model)
        # Output layer
        self.out = nn.Linear(d_model, d_model)
        # Dropout layer
        self.dropout = nn.Dropout(p=dropout_rate)

        self.register_buffer(
            "mask", 
            torch.tril(torch.ones(max_seq_len, max_seq_len)).bool()
        )

    def forward(self, x):
        batch_size, seq_len, d_model = x.shape
        qkv = self.qkv(x) # (batch, seq_len, 3*d_model)

        # Splits the last dimension into (n_heads, head_dim) for (q, k, v)
        qkv = qkv.view(batch_size, seq_len, 3, self.n_heads, self.head_dim)
        q, k, v = qkv.unbind(dim=2)  # (batch, seq_len, n_heads, head_dim)

        # Reshape for multi-head attention.
        q = q.transpose(1, 2)  # (batch, n_heads, seq_len, head_dim)
        k = k.transpose(1, 2)
        v = v.transpose(1, 2)

        # Apply RoPE 
        cos, sin = self.rope(seq_len, x.dtype)
        q, k = apply_rope(q, k, cos, sin)
        
        # Dot-product attention logits  (batch, n_heads, seq_len, seq_len)
        logits = (q @ k.transpose(-2, -1)) / math.sqrt(self.head_dim)

        # Apply causal (look-ahead) mask.  
        mask = self.mask[:seq_len, :seq_len]
        logits_masked = logits.masked_fill(~mask, -torch.inf) 

        # Apply softmax to get attention weights.
        attention_weights = torch.softmax(logits_masked, dim=-1)

        # Apply attention weights to values.
        attn_out = attention_weights @ v  # (batch, n_heads, seq_len, head_dim)

        # Concatenate heads and transpose back to (batch, seq_len, d_model)  
        attn_out = attn_out.transpose(1, 2).contiguous().view(batch_size, seq_len, d_model)

        # output projection (mix heads)
        out = self.out(attn_out)
        
        # Apply dropout
        out = self.dropout(out)

        return out

#### Transformer Block

In [11]:
class TransformerBlock(nn.Module):
    def __init__(self, d_model, n_heads, d_ff, max_seq_len):
        super().__init__()

        self.ln1 = nn.LayerNorm(d_model)
        self.attn = MultiHeadSelfAttention(d_model, n_heads, max_seq_len)
        self.ln2 = nn.LayerNorm(d_model)

        self.mlp = nn.Sequential(
            nn.Linear(d_model, d_ff),
            nn.GELU(),
            nn.Linear(d_ff, d_model),
        )

    def forward(self, x):
        x = x + self.attn(self.ln1(x))
        x = x + self.mlp(self.ln2(x))
        return x

In [12]:
class NanoGPT(nn.Module):
    def __init__(
        self,
        vocab_size,
        d_model,
        n_layers,
        n_heads,
        d_ff,
        max_seq_len,
    ):
        super().__init__()

        self.token_emb = nn.Embedding(vocab_size, d_model)

        self.blocks = nn.ModuleList([
            TransformerBlock(d_model, n_heads, d_ff, max_seq_len)
            for _ in range(n_layers)
        ])

        self.ln_f = nn.LayerNorm(d_model)
        self.lm_head = nn.Linear(d_model, vocab_size, bias=False)
        self.lm_head.weight = self.token_emb.weight # weight tying

    def forward(self, input_ids, labels=None):
        x = self.token_emb(input_ids)  # (batch, seq_len, d_model)

        for block in self.blocks:
            x = block(x)

        x = self.ln_f(x)
        logits = self.lm_head(x)  # (batch, seq_len, vocab_size)

        loss = None
        if labels is not None:
            shift_logits = logits[:, :-1, :].contiguous()  # (batch, seq_len, vocab_size)
            shift_labels = labels[:, 1:].contiguous()      # (batch, seq_len)

            loss = nn.functional.cross_entropy(
                shift_logits.view(-1, shift_logits.size(-1)),
                shift_labels.view(-1),
                ignore_index=-100
            )

        return logits, loss

In [14]:
model = NanoGPT(32000, 384, 8, 6, 4*384, 1024)
res = model(batch["input_ids"], batch["input_ids"])
res

(tensor([[[  5.5034,   2.9038,  -7.1319,  ..., -10.9233,  49.1426,  24.8679],
          [  5.2268,  15.3389, -39.6597,  ...,  37.8705,  14.9848,  -9.2436],
          [ 22.7625,  42.7413,   2.5185,  ...,  13.4140,  30.1241,  21.8427],
          ...,
          [ 26.4857,   6.4850, -11.2536,  ...,  31.4033, -17.8128,  14.2396],
          [ -9.3248,  -4.7640, -31.7205,  ...,  21.2550,  -8.0157, -11.9306],
          [-18.8358, -23.5857,   6.7915,  ..., -10.1819, -55.9789, -20.9245]],

         [[ 35.9726,   0.7576,  -3.9627,  ..., -23.4382,  13.7721, -23.6053],
          [ 16.6530, -34.0718, -12.0033,  ..., -19.0853,  -7.4725, -11.8351],
          [ 23.7371,  -3.6885,   0.9990,  ..., -14.8748, -41.1533, -10.3013],
          ...,
          [-25.7032, -11.4097, -42.2354,  ..., -28.5113,  21.2247,  19.1235],
          [ -9.3761,  -0.3151,  11.8557,  ...,  32.2371,   3.8303,  17.7874],
          [ 14.8167,  -7.5119,   5.4534,  ...,  18.5498,  19.9748,   2.6866]],

         [[  5.6923,  -5.5142, -22.4769,  ...,  -1.9949,  32.0442,  25.9967],
          [-25.9864,  -5.5672,  17.7852,  ..., -17.4595,  12.2329,   5.3248],
          [-30.8792,  16.3267, -48.3130,  ...,  12.7125, -26.8234,   8.5109],
          ...,
          [ 40.5063, -36.4350, -11.9373,  ..., -12.5619, -16.3005,   7.7637],
          [  1.7204,  -6.7619, -24.8804,  ..., -24.5819,  25.0570,  -1.2701],
          [-13.3095,  12.1222,  18.8839,  ...,  -2.5899,  26.3674,   1.1801]],

         [[  3.6406,  -7.0632,   1.0699,  ...,   7.8944, -32.4060,  12.4055],
          [ 11.4323,  11.4389,   4.5635,  ...,  12.6955,  12.2810,  -9.2246],
          [ 15.7016,  27.3445, -33.8601,  ...,   0.3046, -14.1338,  22.8789],
          ...,
          [-22.6645,   4.3106,  12.3696,  ...,   3.9364,  15.2370, -22.0821],
          [ 33.1146,  -2.7454,  22.7652,  ...,   5.2654,  44.5921, -39.0903],
          [  8.2702,   9.3980, -14.8897,  ...,  -1.3965, -15.3834, -31.1752]]],
        grad_fn=<UnsafeViewBackward0>),
 tensor(327.6483, grad_fn=<NllLossBackward0>))

In [15]:
embedding = nn.Embedding(32000, 384)
trn_block = TransformerBlock(384, 6, 4*384, 1024)
x = embedding(batch["input_ids"])
print(x.shape)
z = trn_block(x)
z

torch.Size([4, 1024, 384])

tensor([[[-4.1966e-01, -4.6270e-01,  4.7509e-01,  ..., -4.4352e-01,
          -1.2636e+00,  1.5266e+00],
         [ 9.0714e-01, -9.0094e-01, -7.9066e-02,  ..., -1.0773e+00,
           1.0117e+00,  2.3203e-01],
         [-8.0254e-01,  2.4274e+00, -1.4178e+00,  ...,  5.7267e-01,
          -1.8980e+00,  4.6185e-01],
         ...,
         [-3.1391e-02,  1.4023e+00,  9.5525e-02,  ...,  5.2790e-01,
           2.0667e+00, -1.4871e+00],
         [-5.1097e-01,  4.4899e-01, -6.4000e-01,  ..., -1.3501e-01,
          -1.8494e+00,  1.6669e-01],
         [ 1.7043e-01, -8.9672e-01,  1.4199e+00,  ..., -3.4683e-01,
           3.5259e-01,  2.4633e-01]],

        [[-2.5203e-01, -5.9939e-01,  2.1475e+00,  ..., -4.3060e-01,
          -5.5521e-01,  3.1438e-03],
         [ 1.3496e+00,  5.7182e-01, -5.0428e-01,  ...,  1.3914e-01,
          -1.4544e+00, -7.8179e-04],
         [ 3.6533e-01, -6.0067e-01,  5.8891e-01,  ..., -1.4840e+00,
           3.6566e-01,  6.4860e-01],
         ...,
         [ 8.2798e-01,  1.5269e+00,  1.1728e+00,  ...,  9.4186e-01,
          -1.7068e+00, -1.2153e+00],
         [ 3.2404e+00, -7.3208e-01,  3.0119e-01,  ..., -3.6545e-02,
          -7.6911e-01,  1.4727e+00],
         [-2.2890e-01, -1.0360e+00, -7.5466e-01,  ...,  6.6478e-01,
           6.7772e-01,  6.5269e-01]],

        [[-5.1155e-01,  7.6031e-01, -1.9091e+00,  ...,  1.2509e+00,
          -1.0416e+00,  4.1299e-01],
         [ 1.3535e+00,  4.0439e-01, -1.4228e+00,  ...,  5.0102e-01,
          -4.6497e-01,  1.9440e-01],
         [ 8.8010e-01,  1.2696e+00, -1.7505e+00,  ...,  9.3251e-02,
          -2.1139e+00, -1.2949e+00],
         ...,
         [-6.7848e-01, -7.4357e-01,  3.6250e-02,  ...,  1.6008e-01,
          -7.8954e-01,  3.3802e-01],
         [ 9.4196e-01, -2.9891e-01,  6.7233e-01,  ...,  6.8298e-01,
           5.0221e-01,  3.1388e-01],
         [ 1.1625e+00,  1.1648e+00,  6.3417e-01,  ..., -4.1369e-01,
          -2.1894e+00, -3.1627e-01]],

        [[ 5.4721e-01, -2.2884e+00, -1.3770e-01,  ...,  7.7862e-01,
           4.7058e-01,  2.3488e-01],
         [-8.3257e-01,  1.9253e-01, -1.3383e+00,  ..., -1.1453e-01,
           3.0703e-01,  1.0869e+00],
         [ 1.5127e+00, -3.2362e-01, -5.5037e-01,  ..., -1.2264e-01,
          -1.2856e+00,  1.1081e+00],
         ...,
         [ 1.0071e+00,  1.1505e+00, -2.5726e-01,  ...,  3.7366e-02,
          -2.9154e+00,  3.2359e-02],
         [-2.4440e+00, -5.0072e-01, -2.3683e+00,  ..., -3.5464e-01,
          -1.1012e-01, -4.1051e-01],
         [ 2.1930e-01,  2.3877e+00,  6.9236e-01,  ..., -6.2075e-01,
           3.4325e-01, -1.0462e+00]]], grad_fn=<AddBackward0>)

#### Model anf optimizer initialization

In [ ]:
import torch
from torch.utils.tensorboard import SummaryWriter

writer = SummaryWriter(log_dir="./log/tensorboard")

NUM_EPOCHS = 1
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = NanoGPT(32000, 384, 8, 6, 4*384, 1024).to(device)

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=3e-4,
    betas=(0.9, 0.95),
    weight_decay=0.1
)

total_steps = NUM_EPOCHS * len(gen_loader)
warmup_steps = int(0.01 * total_steps)
decay_steps = total_steps - warmup_steps

warmup_scheduler = torch.optim.lr_scheduler.LinearLR(
    optimizer,
    start_factor=1/4,
    end_factor=1,
    total_iters=warmup_steps
)

cosine_scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer,
    T_max=decay_steps,
    eta_min=1e-5   
)

scheduler = torch.optim.lr_scheduler.SequentialLR(
    optimizer,
    schedulers=[warmup_scheduler, cosine_scheduler],
    milestones=[warmup_steps]
)

#### Training loop

In [18]:
model.train()

global_step = 0

for epoch in range(NUM_EPOCHS):
    for step, batch in enumerate(gen_loader):

        input_ids = batch["input_ids"].to(device)
        optimizer.zero_grad(set_to_none=True)

        logits, loss = model(input_ids, input_ids)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()

        lr = optimizer.param_groups[0]["lr"]
        writer.add_scalar("train/loss", loss.item(), global_step)
        writer.add_scalar("train/lr", lr, global_step)

        if global_step % 10 == 0:
            print(f"step {global_step} | loss {loss.item():.4f} | lr {lr:.6e}")

        global_step += 1

writer.close()

step 0 | loss 138.8189 | lr 7.581191e-05
step 10 | loss 67.7917 | lr 7.682679e-05
step 20 | loss 53.9315 | lr 7.784168e-05
step 30 | loss 47.5924 | lr 7.885656e-05
step 40 | loss 43.5793 | lr 7.987145e-05
step 50 | loss 42.1124 | lr 8.088633e-05
step 60 | loss 39.8638 | lr 8.190122e-05
step 70 | loss 40.5360 | lr 8.291610e-05
step 80 | loss 39.5546 | lr 8.393099e-05
step 90 | loss 36.6884 | lr 8.494587e-05
step 100 | loss 35.1651 | lr 8.596076e-05
step 110 | loss 35.8007 | lr 8.697564e-05
step 120 | loss 36.1261 | lr 8.799053e-05
step 130 | loss 36.1400 | lr 8.900541e-05
step 140 | loss 34.6010 | lr 9.002030e-05
step 150 | loss 34.6821 | lr 9.103518e-05
step 160 | loss 33.8842 | lr 9.205007e-05
step 170 | loss 32.6962 | lr 9.306495e-05
step 180 | loss 31.2556 | lr 9.407984e-05
step 190 | loss 32.5713 | lr 9.509472e-05
step 200 | loss 30.2331 | lr 9.610961e-05
step 210 | loss 31.4335 | lr 9.712449e-05
step 220 | loss 31.8710 | lr 9.813938e-05
step 230 | loss 31.0114 | lr 9.915426e-05
step 240 | loss 30.1359 | lr 1.001691e-04
step 250 | loss 29.9150 | lr 1.011840e-04
step 260 | loss 30.1691 | lr 1.021989e-04
step 270 | loss 29.4846 | lr 1.032138e-04
step 280 | loss 28.1649 | lr 1.042287e-04
step 290 | loss 27.9327 | lr 1.052436e-04
step 300 | loss 28.6387 | lr 1.062585e-04
step 310 | loss 27.7689 | lr 1.072733e-04
step 320 | loss 27.8280 | lr 1.082882e-04
step 330 | loss 26.1963 | lr 1.093031e-04
step 340 | loss 26.6156 | lr 1.103180e-04
step 350 | loss 26.1760 | lr 1.113329e-04
step 360 | loss 27.5692 | lr 1.123478e-04
step 370 | loss 24.4088 | lr 1.133627e-04
step 380 | loss 25.6541 | lr 1.143775e-04
step 390 | loss 23.0310 | lr 1.153924e-04
step 400 | loss 25.5760 | lr 1.164073e-04
step 410 | loss 24.7526 | lr 1.174222e-04
step 420 | loss 22.8893 | lr 1.184371e-04
step 430 | loss 22.9963 | lr 1.194520e-04
step 440 | loss 23.5310 | lr 1.204668e-04
step 450 | loss 23.0276 | lr 1.214817e-04
step 460 | loss 21.1863 | lr 1.224966e-04
step 470 | loss 22.0586 | lr 1.235115e-04
step 480 | loss 21.1242 | lr 1.245264e-04
step 490 | loss 21.6273 | lr 1.255413e-04
step 500 | loss 21.2759 | lr 1.265562e-04
step 510 | loss 21.3851 | lr 1.275710e-04
step 520 | loss 19.3438 | lr 1.285859e-04
step 530 | loss 20.5717 | lr 1.296008e-04
step 540 | loss 20.5405 | lr 1.306157e-04
step 550 | loss 19.0011 | lr 1.316306e-04
step 560 | loss 19.7021 | lr 1.326455e-04
step 570 | loss 18.9368 | lr 1.336604e-04
step 580 | loss 19.0192 | lr 1.346752e-04
step 590 | loss 18.9814 | lr 1.356901e-04
step 600 | loss 18.5272 | lr 1.367050e-04
step 610 | loss 17.8196 | lr 1.377199e-04
step 620 | loss 17.8890 | lr 1.387348e-04
step 630 | loss 17.5243 | lr 1.397497e-04
step 640 | loss 17.5643 | lr 1.407645e-04
step 650 | loss 16.7264 | lr 1.417794e-04
step 660 | loss 16.7722 | lr 1.427943e-04
step 670 | loss 16.8406 | lr 1.438092e-04
step 680 | loss 16.4280 | lr 1.448241e-04
step 690 | loss 15.9442 | lr 1.458390e-04
step 700 | loss 16.2145 | lr 1.468539e-04
step 710 | loss 13.7370 | lr 1.478687e-04
step 720 | loss 15.4915 | lr 1.488836e-04
step 730 | loss 14.5831 | lr 1.498985e-04
step 740 | loss 15.3735 | lr 1.509134e-04
step 750 | loss 15.0106 | lr 1.519283e-04
step 760 | loss 15.0760 | lr 1.529432e-04
step 770 | loss 14.8110 | lr 1.539581e-04
step 780 | loss 14.6671 | lr 1.549729e-04
step 790 | loss 13.9238 | lr 1.559878e-04
step 800 | loss 14.2325 | lr 1.570027e-04
step 810 | loss 13.9848 | lr 1.580176e-04
step 820 | loss 13.9677 | lr 1.590325e-04
step 830 | loss 13.0963 | lr 1.600474e-04
step 840 | loss 12.7472 | lr 1.610622e-04
step 850 | loss 12.7844 | lr 1.620771e-04
step 860 | loss 13.1023 | lr 1.630920e-04
step 870 | loss 13.6047 | lr 1.641069e-04
step 880 | loss 12.3798 | lr 1.651218e-04
step 890 | loss 13.1928 | lr 1.661367e-04
step 900 | loss 13.0160 | lr 1.671516e-04
step 910 | loss 12.6601 | lr 1.681664e-04
step 920 | loss 11.9653 | lr 1.691813e-04
step 930 | loss 12.4320 | lr 1.701962e-04
step 940 | loss 11.4702 | lr 1.712111e-04
step 950 | loss 12.2299 | lr 1.722260e-04
step 960 | loss 11.6901 | lr 1.732409e-04
step 970 | loss 12.2492 | lr 1.742558e-04
step 980 | loss 11.7403 | lr 1.752706e-04
step 990 | loss 11.8288 | lr 1.762855e-04
step 1000 | loss 11.5033 | lr 1.773004e-04
step 1010 | loss 11.8033 | lr 1.783153e-04
step 1020 | loss 11.5560 | lr 1.793302e-04
step 1030 | loss 11.2915 | lr 1.803451e-04
step 1040 | loss 11.0182 | lr 1.813599e-04
step 1050 | loss 11.2589 | lr 1.823748e-04
step 1060 | loss 11.3133 | lr 1.833897e-04
step 1070 | loss 11.0229 | lr 1.844046e-04
step 1080 | loss 10.4936 | lr 1.854195e-04
step 1090 | loss 11.1824 | lr 1.864344e-04
step 1100 | loss 10.5781 | lr 1.874493e-04
step 1110 | loss 10.6786 | lr 1.884641e-04
step 1120 | loss 10.6737 | lr 1.894790e-04
step 1130 | loss 10.0564 | lr 1.904939e-04
step 1140 | loss 10.1466 | lr 1.915088e-04
step 1150 | loss 10.4595 | lr 1.925237e-04
step 1160 | loss 10.4944 | lr 1.935386e-04
step 1170 | loss 10.3913 | lr 1.945535e-04
step 1180 | loss 10.2658 | lr 1.955683e-04
step 1190 | loss 10.3883 | lr 1.965832e-04
step 1200 | loss 9.7009 | lr 1.975981e-04
step 1210 | loss 9.7322 | lr 1.986130e-04
step 1220 | loss 10.0490 | lr 1.996279e-04
step 1230 | loss 10.1797 | lr 2.006428e-04
step 1240 | loss 9.8613 | lr 2.016576e-04
step 1250 | loss 9.3113 | lr 2.026725e-04
step 1260 | loss 9.5919 | lr 2.036874e-04
step 1270 | loss 9.9157 | lr 2.047023e-04
step 1280 | loss 9.7559 | lr 2.057172e-04
step 1290 | loss 9.4109 | lr 2.067321e-04
step 1300 | loss 9.2453 | lr 2.077470e-04
step 1310 | loss 9.2497 | lr 2.087618e-04
step 1320 | loss 9.6303 | lr 2.097767e-04
step 1330 | loss 9.8914 | lr 2.107916e-04
step 1340 | loss 9.3766 | lr 2.118065e-04
step 1350 | loss 9.2848 | lr 2.128214e-04
step 1360 | loss 9.5529 | lr 2.138363e-04
step 1370 | loss 9.5566 | lr 2.148512e-04
step 1380 | loss 9.0565 | lr 2.158660e-04
step 1390 | loss 9.5996 | lr 2.168809e-04
step 1400 | loss 9.3088 | lr 2.178958e-04
step 1410 | loss 8.9405 | lr 2.189107e-04
step 1420 | loss 9.1409 | lr 2.199256e-04
step 1430 | loss 8.6843 | lr 2.209405e-04
step 1440 | loss 9.2193 | lr 2.219553e-04
step 1450 | loss 8.7743 | lr 2.229702e-04
step 1460 | loss 8.9066 | lr 2.239851e-04
step 1470 | loss 8.8431 | lr 2.250000e-04
step 1480 | loss 8.8300 | lr 2.260149e-04
step 1490 | loss 9.1509 | lr 2.270298e-04
step 1500 | loss 8.5540 | lr 2.280447e-04
step 1510 | loss 9.0535 | lr 2.290595e-04
step 1520 | loss 9.1049 | lr 2.300744e-04
step 1530 | loss 8.9757 | lr 2.310893e-04
step 1540 | loss 8.8378 | lr 2.321042e-04
step 1550 | loss 8.6629 | lr 2.331191e-04
step 1560 | loss 8.9005 | lr 2.341340e-04
step 1570 | loss 8.8579 | lr 2.351488e-04
step 1580 | loss 8.7685 | lr 2.361637e-04
step 1590 | loss 8.6856 | lr 2.371786e-04
step 1600 | loss 8.3785 | lr 2.381935e-04
step 1610 | loss 8.7375 | lr 2.392084e-04
step 1620 | loss 8.8298 | lr 2.402233e-04
step 1630 | loss 8.1428 | lr 2.412382e-04
step 1640 | loss 8.9540 | lr 2.422530e-04
step 1650 | loss 8.8954 | lr 2.432679e-04
step 1660 | loss 8.6162 | lr 2.442828e-04
step 1670 | loss 8.5234 | lr 2.452977e-04
step 1680 | loss 8.5788 | lr 2.463126e-04
step 1690 | loss 8.1769 | lr 2.473275e-04
step 1700 | loss 8.2742 | lr 2.483424e-04
step 1710 | loss 8.7359 | lr 2.493572e-04
step 1720 | loss 8.3482 | lr 2.503721e-04
step 1730 | loss 8.3595 | lr 2.513870e-04
step 1740 | loss 8.6663 | lr 2.524019e-04
step 1750 | loss 8.1954 | lr 2.534168e-04
step 1760 | loss 8.3099 | lr 2.544317e-04
step 1770 | loss 8.2388 | lr 2.554465e-04
step 1780 | loss 8.3088 | lr 2.564614e-04
step 1790 | loss 8.5260 | lr 2.574763e-04
step 1800 | loss 8.2173 | lr 2.584912e-04
step 1810 | loss 8.2873 | lr 2.595061e-04
step 1820 | loss 8.1813 | lr 2.605210e-04
step 1830 | loss 8.1507 | lr 2.615359e-04
step 1840 | loss 8.5070 | lr 2.625507e-04
step 1850 | loss 8.3701 | lr 2.635656e-04
step 1860 | loss 8.5711 | lr 2.645805e-04
step 1870 | loss 8.3930 | lr 2.655954e-04
step 1880 | loss 8.0801 | lr 2.666103e-04
step 1890 | loss 8.1000 | lr 2.676252e-04
step 1900 | loss 8.4822 | lr 2.686401e-04
step 1910 | loss 7.7792 | lr 2.696549e-04
step 1920 | loss 8.0607 | lr 2.706698e-04
step 1930 | loss 8.3830 | lr 2.716847e-04
step 1940 | loss 8.1784 | lr 2.726996e-04
step 1950 | loss 8.0872 | lr 2.737145e-04
step 1960 | loss 7.7865 | lr 2.747294e-04
step 1970 | loss 7.6629 | lr 2.757442e-04
step 1980 | loss 8.0420 | lr 2.767591e-04
step 1990 | loss 8.0260 | lr 2.777740e-04
step 2000 | loss 7.9198 | lr 2.787889e-04
step 2010 | loss 8.0152 | lr 2.798038e-04
step 2020 | loss 7.7631 | lr 2.808187e-04
step 2030 | loss 7.7450 | lr 2.818336e-04
step 2040 | loss 8.0975 | lr 2.828484e-04
step 2050 | loss 7.9861 | lr 2.838633e-04
step 2060 | loss 7.8387 | lr 2.848782e-04
step 2070 | loss 8.1046 | lr 2.858931e-04
step 2080 | loss 7.9833 | lr 2.869080e-04
step 2090 | loss 7.8366 | lr 2.879229e-04
step 2100 | loss 8.0396 | lr 2.889378e-04
step 2110 | loss 8.1973 | lr 2.899526e-04
step 2120 | loss 8.0770 | lr 2.909675e-04
step 2130 | loss 7.8352 | lr 2.919824e-04
step 2140 | loss 8.0492 | lr 2.929973e-04
step 2150 | loss 7.8124 | lr 2.940122e-04
step 2160 | loss 7.8753 | lr 2.950271e-04
step 2170 | loss 7.8074 | lr 2.960419e-04
step 2180 | loss 7.5686 | lr 2.970568e-04
step 2190 | loss 7.9806 | lr 2.980717e-04
step 2200 | loss 7.6836 | lr 2.990866e-04

c:\Users\Akulich_SA\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\optim\lr_scheduler.py:198: UserWarning: The epoch parameter in `scheduler.step()` was not necessary and is being deprecated where possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form, where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.
  warnings.warn(EPOCH_DEPRECATION_WARNING, UserWarning)

step 2210 | loss 7.9865 | lr 3.000000e-04
step 2220 | loss 7.5564 | lr 3.000000e-04
step 2230 | loss 8.2666 | lr 3.000000e-04
step 2240 | loss 7.9244 | lr 3.000000e-04
step 2250 | loss 8.0487 | lr 3.000000e-04
step 2260 | loss 7.8733 | lr 3.000000e-04
step 2270 | loss 7.7835 | lr 2.999999e-04
step 2280 | loss 7.6890 | lr 2.999999e-04
step 2290 | loss 7.9879 | lr 2.999999e-04
step 2300 | loss 7.7387 | lr 2.999999e-04
step 2310 | loss 8.3254 | lr 2.999998e-04
step 2320 | loss 7.9987 | lr 2.999998e-04
step 2330 | loss 8.1268 | lr 2.999998e-04
step 2340 | loss 7.9097 | lr 2.999997e-04
step 2350 | loss 7.9779 | lr 2.999997e-04
step 2360 | loss 7.9514 | lr 2.999997e-04
step 2370 | loss 7.5335 | lr 2.999996e-04
step 2380 | loss 8.0208 | lr 2.999996e-04
step 2390 | loss 8.1457 | lr 2.999995e-04
step 2400 | loss 7.7671 | lr 2.999995e-04
step 2410 | loss 8.0640 | lr 2.999994e-04
step 2420 | loss 8.1000 | lr 2.999993e-04
step 2430 | loss 8.0114 | lr 2.999993e-04
step 2440 | loss 7.6142 | lr 2.999992e-04
step 2450 | loss 8.0020 | lr 2.999991e-04
step 2460 | loss 8.0564 | lr 2.999991e-04
step 2470 | loss 7.6539 | lr 2.999990e-04
step 2480 | loss 7.7428 | lr 2.999989e-04
step 2490 | loss 7.9524 | lr 2.999988e-04
step 2500 | loss 8.0015 | lr 2.999987e-04
step 2510 | loss 8.0805 | lr 2.999987e-04
step 2520 | loss 8.0350 | lr 2.999986e-04
step 2530 | loss 7.5361 | lr 2.999985e-04
step 2540 | loss 7.8322 | lr 2.999984e-04
step 2550 | loss 7.9176 | lr 2.999983e-04
step 2560 | loss 7.9221 | lr 2.999982e-04
step 2570 | loss 7.3003 | lr 2.999981e-04
step 2580 | loss 7.8226 | lr 2.999980e-04
step 2590 | loss 7.7623 | lr 2.999978e-04
step 2600 | loss 7.7663 | lr 2.999977e-04
step 2610 | loss 8.0158 | lr 2.999976e-04
step 2620 | loss 7.9923 | lr 2.999975e-04
step 2630 | loss 7.9446 | lr 2.999974e-04
step 2640 | loss 7.7414 | lr 2.999972e-04
step 2650 | loss 7.7359 | lr 2.999971e-04
step 2660 | loss 7.8549 | lr 2.999970e-04
step 2670 | loss 7.5574 | lr 2.999968e-04
step 2680 | loss 7.2919 | lr 2.999967e-04
step 2690 | loss 7.8407 | lr 2.999966e-04
step 2700 | loss 7.5724 | lr 2.999964e-04
step 2710 | loss 7.6843 | lr 2.999963e-04
step 2720 | loss 7.8894 | lr 2.999961e-04
step 2730 | loss 7.9070 | lr 2.999960e-04
step 2740 | loss 7.3520 | lr 2.999958e-04
step 2750 | loss 7.3379 | lr 2.999957e-04
step 2760 | loss 7.5374 | lr 2.999955e-04
step 2770 | loss 7.7587 | lr 2.999953e-04
step 2780 | loss 7.7643 | lr 2.999952e-04
step 2790 | loss 7.8327 | lr 2.999950e-04
step 2800 | loss 7.9072 | lr 2.999948e-04
step 2810 | loss 7.2901 | lr 2.999946e-04
step 2820 | loss 7.8910 | lr 2.999945e-04
step 2830 | loss 7.4728 | lr 2.999943e-04
step 2840 | loss 7.6125 | lr 2.999941e-04
step 2850 | loss 7.6993 | lr 2.999939e-04
step 2860 | loss 7.3428 | lr 2.999937e-04
step 2870 | loss 7.6027 | lr 2.999935e-04
step 2880 | loss 7.8656 | lr 2.999933e-04
step 2890 | loss 7.7883 | lr 2.999931e-04
step 2900 | loss 7.0073 | lr 2.999929e-04
step 2910 | loss 7.6263 | lr 2.999927e-04
step 2920 | loss 7.7602 | lr 2.999925e-04
step 2930 | loss 7.5181 | lr 2.999923e-04
step 2940 | loss 7.3060 | lr 2.999921e-04
step 2950 | loss 7.6840 | lr 2.999918e-04
step 2960 | loss 7.6226 | lr 2.999916e-04
step 2970 | loss 7.5297 | lr 2.999914e-04
step 2980 | loss 7.7808 | lr 2.999912e-04
step 2990 | loss 7.2996 | lr 2.999909e-04
step 3000 | loss 7.3906 | lr 2.999907e-04
step 3010 | loss 7.6308 | lr 2.999905e-04
step 3020 | loss 7.6784 | lr 2.999902e-04
step 3030 | loss 7.4611 | lr 2.999900e-04
step 3040 | loss 7.6485 | lr 2.999897e-04
step 3050 | loss 7.8818 | lr 2.999895e-04
step 3060 | loss 7.6997 | lr 2.999892e-04
step 3070 | loss 7.7213 | lr 2.999890e-04
step 3080 | loss 7.5923 | lr 2.999887e-04
step 3090 | loss 7.5463 | lr 2.999885e-04
step 3100 | loss 7.5125 | lr 2.999882e-04
step 3110 | loss 7.7040 | lr 2.999879e-04
step 3120 | loss 7.2717 | lr 2.999877e-04
step 3130 | loss 7.5967 | lr 2.999874e-04
step 3140 | loss 7.7650 | lr 2.999871e-04
step 3150 | loss 7.6283 | lr 2.999869e-04
step 3160 | loss 7.2338 | lr 2.999866e-04
step 3170 | loss 7.1543 | lr 2.999863e-04
step 3180 | loss 7.5491 | lr 2.999860e-04
step 3190 | loss 7.6788 | lr 2.999857e-04
step 3200 | loss 7.4141 | lr 2.999854e-04
step 3210 | loss 7.1104 | lr 2.999851e-04
step 3220 | loss 7.5846 | lr 2.999848e-04
step 3230 | loss 7.6895 | lr 2.999845e-04
step 3240 | loss 7.2031 | lr 2.999842e-04
step 3250 | loss 7.3253 | lr 2.999839e-04
step 3260 | loss 7.5144 | lr 2.999836e-04
step 3270 | loss 7.7701 | lr 2.999833e-04
step 3280 | loss 7.3213 | lr 2.999830e-04
step 3290 | loss 7.4946 | lr 2.999826e-04
step 3300 | loss 7.6653 | lr 2.999823e-04
step 3310 | loss 7.4426 | lr 2.999820e-04
step 3320 | loss 7.4956 | lr 2.999817e-04
step 3330 | loss 7.6040 | lr 2.999813e-04
step 3340 | loss 7.2941 | lr 2.999810e-04
step 3350 | loss 7.6389 | lr 2.999807e-04
step 3360 | loss 7.3350 | lr 2.999803e-04
step 3370 | loss 7.3479 | lr 2.999800e-04
step 3380 | loss 7.3422 | lr 2.999796e-04
step 3390 | loss 7.5330 | lr 2.999793e-04
step 3400 | loss 7.4705 | lr 2.999789e-04
step 3410 | loss 7.5915 | lr 2.999786e-04
step 3420 | loss 7.4055 | lr 2.999782e-04
step 3430 | loss 8.1233 | lr 2.999779e-04
step 3440 | loss 7.5297 | lr 2.999775e-04
step 3450 | loss 7.4720 | lr 2.999771e-04
step 3460 | loss 7.5152 | lr 2.999768e-04
step 3470 | loss 7.7941 | lr 2.999764e-04
step 3480 | loss 7.6434 | lr 2.999760e-04
step 3490 | loss 7.4622 | lr 2.999756e-04
step 3500 | loss 7.2256 | lr 2.999752e-04
step 3510 | loss 7.5012 | lr 2.999749e-04
step 3520 | loss 7.3693 | lr 2.999745e-04
step 3530 | loss 7.4237 | lr 2.999741e-04
step 3540 | loss 7.4856 | lr 2.999737e-04
step 3550 | loss 7.2636 | lr 2.999733e-04
step 3560 | loss 6.8031 | lr 2.999729e-04
step 3570 | loss 7.1764 | lr 2.999725e-04
step 3580 | loss 7.5656 | lr 2.999721e-04
step 3590 | loss 7.2608 | lr 2.999717e-04
step 3600 | loss 7.2728 | lr 2.999713e-04
step 3610 | loss 7.3836 | lr 2.999709e-04
step 3620 | loss 7.5047 | lr 2.999704e-04
step 3630 | loss 7.6835 | lr 2.999700e-04
step 3640 | loss 7.3593 | lr 2.999696e-04
step 3650 | loss 7.3660 | lr 2.999692e-04
step 3660 | loss 7.1995 | lr 2.999687e-04
step 3670 | loss 7.6202 | lr 2.999683e-04
step 3680 | loss 7.3402 | lr 2.999679e-04
step 3690 | loss 7.2363 | lr 2.999674e-04
step 3700 | loss 7.2525 | lr 2.999670e-04
step 3710 | loss 7.0434 | lr 2.999665e-04
step 3720 | loss 7.2454 | lr 2.999661e-04
step 3730 | loss 7.4069 | lr 2.999656e-04
step 3740 | loss 7.5599 | lr 2.999652e-04
step 3750 | loss 7.1602 | lr 2.999647e-04
step 3760 | loss 7.1214 | lr 2.999643e-04
step 3770 | loss 7.2607 | lr 2.999638e-04
step 3780 | loss 7.1434 | lr 2.999633e-04
step 3790 | loss 7.3381 | lr 2.999629e-04
step 3800 | loss 7.3242 | lr 2.999624e-04
step 3810 | loss 7.2915 | lr 2.999619e-04
step 3820 | loss 7.3125 | lr 2.999615e-04
step 3830 | loss 7.5011 | lr 2.999610e-04
step 3840 | loss 7.2383 | lr 2.999605e-04
step 3850 | loss 7.5876 | lr 2.999600e-04
step 3860 | loss 7.4142 | lr 2.999595e-04
step 3870 | loss 7.3860 | lr 2.999590e-04
step 3880 | loss 7.3508 | lr 2.999585e-04
step 3890 | loss 7.4498 | lr 2.999580e-04
step 3900 | loss 7.1058 | lr 2.999575e-04
step 3910 | loss 7.6216 | lr 2.999570e-04
step 3920 | loss 7.4434 | lr 2.999565e-04
step 3930 | loss 7.0894 | lr 2.999560e-04
step 3940 | loss 7.3983 | lr 2.999555e-04
step 3950 | loss 7.2661 | lr 2.999550e-04
step 3960 | loss 7.2426 | lr 2.999545e-04
step 3970 | loss 7.4032 | lr 2.999539e-04
step 3980 | loss 7.5386 | lr 2.999534e-04
step 3990 | loss 7.1793 | lr 2.999529e-04
step 4000 | loss 7.0696 | lr 2.999524e-04
step 4010 | loss 7.4861 | lr 2.999518e-04
step 4020 | loss 7.1883 | lr 2.999513e-04
step 4030 | loss 7.3839 | lr 2.999508e-04
step 4040 | loss 7.5349 | lr 2.999502e-04
step 4050 | loss 7.0447 | lr 2.999497e-04
step 4060 | loss 7.3826 | lr 2.999491e-04
step 4070 | loss 7.2238 | lr 2.999486e-04
step 4080 | loss 7.0918 | lr 2.999480e-04
step 4090 | loss 7.2644 | lr 2.999475e-04
step 4100 | loss 7.2848 | lr 2.999469e-04
step 4110 | loss 7.4060 | lr 2.999463e-04
step 4120 | loss 7.4782 | lr 2.999458e-04
step 4130 | loss 7.3137 | lr 2.999452e-04
step 4140 | loss 7.5539 | lr 2.999446e-04
step 4150 | loss 7.1569 | lr 2.999441e-04
step 4160 | loss 7.4639 | lr 2.999435e-04
step 4170 | loss 7.2648 | lr 2.999429e-04
step 4180 | loss 6.9744 | lr 2.999423e-04
step 4190 | loss 7.0249 | lr 2.999417e-04
step 4200 | loss 7.2065 | lr 2.999411e-04
step 4210 | loss 7.3193 | lr 2.999405e-04
step 4220 | loss 7.3512 | lr 2.999399e-04
step 4230 | loss 6.5966 | lr 2.999393e-04
step 4240 | loss 6.8776 | lr 2.999387e-04
step 4250 | loss 7.3411 | lr 2.999381e-04
step 4260 | loss 7.1943 | lr 2.999375e-04
step 4270 | loss 7.2947 | lr 2.999369e-04
step 4280 | loss 7.2143 | lr 2.999363e-04
step 4290 | loss 6.8515 | lr 2.999357e-04
step 4300 | loss 7.0648 | lr 2.999351e-04
step 4310 | loss 7.0871 | lr 2.999345e-04
step 4320 | loss 7.2992 | lr 2.999338e-04
step 4330 | loss 7.1233 | lr 2.999332e-04
step 4340 | loss 6.9388 | lr 2.999326e-04
step 4350 | loss 7.4354 | lr 2.999319e-04
step 4360 | loss 6.9086 | lr 2.999313e-04
step 4370 | loss 6.8090 | lr 2.999307e-04
step 4380 | loss 7.1647 | lr 2.999300e-04
step 4390 | loss 6.9997 | lr 2.999294e-04
step 4400 | loss 6.9303 | lr 2.999287e-04
step 4410 | loss 7.1676 | lr 2.999281e-04
step 4420 | loss 7.4017 | lr 2.999274e-04
step 4430 | loss 6.9915 | lr 2.999268e-04
step 4440 | loss 7.1888 | lr 2.999261e-04
step 4450 | loss 6.6559 | lr 2.999254e-04
step 4460 | loss 7.0938 | lr 2.999248e-04
step 4470 | loss 7.1962 | lr 2.999241e-04
step 4480 | loss 7.4983 | lr 2.999234e-04
step 4490 | loss 7.3832 | lr 2.999227e-04
step 4500 | loss 7.1123 | lr 2.999221e-04
step 4510 | loss 6.8029 | lr 2.999214e-04
step 4520 | loss 7.1781 | lr 2.999207e-04
step 4530 | loss 7.4235 | lr 2.999200e-04
step 4540 | loss 7.2464 | lr 2.999193e-04
step 4550 | loss 6.6721 | lr 2.999186e-04
step 4560 | loss 7.1314 | lr 2.999179e-04
step 4570 | loss 6.9557 | lr 2.999172e-04
step 4580 | loss 6.9191 | lr 2.999165e-04
step 4590 | loss 7.2884 | lr 2.999158e-04
step 4600 | loss 7.2745 | lr 2.999151e-04
step 4610 | loss 7.2622 | lr 2.999144e-04
step 4620 | loss 6.9591 | lr 2.999137e-04
step 4630 | loss 7.2616 | lr 2.999130e-04
step 4640 | loss 7.2677 | lr 2.999122e-04
step 4650 | loss 6.9564 | lr 2.999115e-04
step 4660 | loss 6.8370 | lr 2.999108e-04
step 4670 | loss 7.2621 | lr 2.999101e-04
step 4680 | loss 6.9580 | lr 2.999093e-04
step 4690 | loss 7.3592 | lr 2.999086e-04
step 4700 | loss 6.7436 | lr 2.999079e-04
step 4710 | loss 7.2422 | lr 2.999071e-04
step 4720 | loss 7.1394 | lr 2.999064e-04
step 4730 | loss 6.9635 | lr 2.999056e-04
step 4740 | loss 7.2283 | lr 2.999049e-04
step 4750 | loss 6.9981 | lr 2.999041e-04
step 4760 | loss 7.2669 | lr 2.999034e-04
step 4770 | loss 7.2090 | lr 2.999026e-04
step 4780 | loss 6.8678 | lr 2.999018e-04
step 4790 | loss 6.5863 | lr 2.999011e-04
step 4800 | loss 7.1711 | lr 2.999003e-04
step 4810 | loss 6.8618 | lr 2.998995e-04
step 4820 | loss 7.1719 | lr 2.998988e-04
step 4830 | loss 7.0152 | lr 2.998980e-04
step 4840 | loss 7.0193 | lr 2.998972e-04
step 4850 | loss 7.2345 | lr 2.998964e-04
step 4860 | loss 6.6985 | lr 2.998956e-04
step 4870 | loss 7.1092 | lr 2.998949e-04
step 4880 | loss 7.1995 | lr 2.998941e-04
step 4890 | loss 7.0569 | lr 2.998933e-04
step 4900 | loss 6.6761 | lr 2.998925e-04
step 4910 | loss 6.8485 | lr 2.998917e-04
step 4920 | loss 7.0613 | lr 2.998909e-04
step 4930 | loss 6.9851 | lr 2.998901e-04
step 4940 | loss 6.9111 | lr 2.998893e-04
step 4950 | loss 7.2094 | lr 2.998884e-04
step 4960 | loss 6.5988 | lr 2.998876e-04
step 4970 | loss 6.7296 | lr 2.998868e-04
step 4980 | loss 7.1016 | lr 2.998860e-04
step 4990 | loss 6.6139 | lr 2.998852e-04
step 5000 | loss 7.2114 | lr 2.998843e-04
step 5010 | loss 7.0876 | lr 2.998835e-04
step 5020 | loss 6.9510 | lr 2.998827e-04
step 5030 | loss 7.0263 | lr 2.998818e-04
step 5040 | loss 6.8815 | lr 2.998810e-04
step 5050 | loss 6.9163 | lr 2.998802e-04
step 5060 | loss 6.8464 | lr 2.998793e-04
step 5070 | loss 6.9381 | lr 2.998785e-04
step 5080 | loss 6.9377 | lr 2.998776e-04
step 5090 | loss 7.0965 | lr 2.998768e-04
step 5100 | loss 6.8904 | lr 2.998759e-04
step 5110 | loss 7.1107 | lr 2.998750e-04
step 5120 | loss 7.1702 | lr 2.998742e-04
step 5130 | loss 7.2970 | lr 2.998733e-04
step 5140 | loss 6.9078 | lr 2.998724e-04
step 5150 | loss 6.9993 | lr 2.998716e-04
step 5160 | loss 7.0317 | lr 2.998707e-04
step 5170 | loss 7.2368 | lr 2.998698e-04
step 5180 | loss 6.9129 | lr 2.998689e-04
step 5190 | loss 6.7945 | lr 2.998681e-04
step 5200 | loss 6.8106 | lr 2.998672e-04
step 5210 | loss 6.9205 | lr 2.998663e-04
step 5220 | loss 6.7862 | lr 2.998654e-04
step 5230 | loss 6.8987 | lr 2.998645e-04
step 5240 | loss 6.8073 | lr 2.998636e-04
step 5250 | loss 6.9734 | lr 2.998627e-04
step 5260 | loss 6.7663 | lr 2.998618e-04
step 5270 | loss 7.0216 | lr 2.998609e-04
step 5280 | loss 6.8317 | lr 2.998600e-04
step 5290 | loss 7.0096 | lr 2.998591e-04
step 5300 | loss 6.8447 | lr 2.998581e-04
step 5310 | loss 7.0456 | lr 2.998572e-04
step 5320 | loss 7.0398 | lr 2.998563e-04
step 5330 | loss 6.6257 | lr 2.998554e-04
step 5340 | loss 6.9697 | lr 2.998544e-04
step 5350 | loss 7.1148 | lr 2.998535e-04
step 5360 | loss 6.9077 | lr 2.998526e-04
step 5370 | loss 6.7401 | lr 2.998516e-04
step 5380 | loss 6.3821 | lr 2.998507e-04
step 5390 | loss 6.9466 | lr 2.998498e-04
step 5400 | loss 7.1646 | lr 2.998488e-04
step 5410 | loss 6.8577 | lr 2.998479e-04
step 5420 | loss 6.9596 | lr 2.998469e-04
step 5430 | loss 6.7930 | lr 2.998460e-04
step 5440 | loss 6.7271 | lr 2.998450e-04
step 5450 | loss 6.9502 | lr 2.998440e-04
step 5460 | loss 6.8595 | lr 2.998431e-04
step 5470 | loss 6.9257 | lr 2.998421e-04
step 5480 | loss 6.4862 | lr 2.998411e-04
step 5490 | loss 6.6972 | lr 2.998402e-04
step 5500 | loss 6.9741 | lr 2.998392e-04
step 5510 | loss 6.7957 | lr 2.998382e-04
step 5520 | loss 6.9398 | lr 2.998372e-04
step 5530 | loss 6.8633 | lr 2.998362e-04
step 5540 | loss 6.8095 | lr 2.998353e-04
step 5550 | loss 6.5275 | lr 2.998343e-04
step 5560 | loss 6.9780 | lr 2.998333e-04
step 5570 | loss 6.6871 | lr 2.998323e-04
step 5580 | loss 6.7094 | lr 2.998313e-04
step 5590 | loss 6.7532 | lr 2.998303e-04
step 5600 | loss 6.7343 | lr 2.998293e-04
step 5610 | loss 6.5382 | lr 2.998283e-04
step 5620 | loss 7.0875 | lr 2.998272e-04
step 5630 | loss 6.7275 | lr 2.998262e-04
step 5640 | loss 6.5809 | lr 2.998252e-04
step 5650 | loss 6.9660 | lr 2.998242e-04
step 5660 | loss 6.5768 | lr 2.998232e-04
step 5670 | loss 7.2323 | lr 2.998221e-04
step 5680 | loss 6.9039 | lr 2.998211e-04
step 5690 | loss 6.9935 | lr 2.998201e-04
step 5700 | loss 6.8206 | lr 2.998191e-04
step 5710 | loss 6.7740 | lr 2.998180e-04
step 5720 | loss 7.0408 | lr 2.998170e-04
step 5730 | loss 6.7564 | lr 2.998159e-04
step 5740 | loss 6.6413 | lr 2.998149e-04
step 5750 | loss 6.6620 | lr 2.998138e-04
step 5760 | loss 6.5809 | lr 2.998128e-04
step 5770 | loss 6.9780 | lr 2.998117e-04
step 5780 | loss 6.9477 | lr 2.998107e-04
step 5790 | loss 6.8493 | lr 2.998096e-04
step 5800 | loss 6.7578 | lr 2.998085e-04
step 5810 | loss 7.1491 | lr 2.998075e-04
step 5820 | loss 6.5300 | lr 2.998064e-04
step 5830 | loss 6.5555 | lr 2.998053e-04
step 5840 | loss 6.7474 | lr 2.998043e-04
step 5850 | loss 7.0281 | lr 2.998032e-04
step 5860 | loss 6.7651 | lr 2.998021e-04
step 5870 | loss 7.0100 | lr 2.998010e-04
step 5880 | loss 6.4189 | lr 2.997999e-04
step 5890 | loss 6.8332 | lr 2.997988e-04
step 5900 | loss 6.9023 | lr 2.997977e-04
step 5910 | loss 6.7019 | lr 2.997966e-04
step 5920 | loss 6.5185 | lr 2.997955e-04
step 5930 | loss 6.7312 | lr 2.997944e-04
step 5940 | loss 6.7503 | lr 2.997933e-04
step 5950 | loss 6.3507 | lr 2.997922e-04
step 5960 | loss 6.5785 | lr 2.997911e-04
step 5970 | loss 6.6781 | lr 2.997900e-04
step 5980 | loss 6.8327 | lr 2.997889e-04
step 5990 | loss 6.6474 | lr 2.997877e-04
step 6000 | loss 6.5380 | lr 2.997866e-04
step 6010 | loss 6.8732 | lr 2.997855e-04
step 6020 | loss 6.8871 | lr 2.997844e-04
step 6030 | loss 6.5858 | lr 2.997832e-04
step 6040 | loss 6.6221 | lr 2.997821e-04
step 6050 | loss 6.3274 | lr 2.997810e-04
step 6060 | loss 6.6357 | lr 2.997798e-04
step 6070 | loss 6.8459 | lr 2.997787e-04
step 6080 | loss 6.5291 | lr 2.997775e-04
step 6090 | loss 6.3668 | lr 2.997764e-04
step 6100 | loss 6.1572 | lr 2.997752e-04
step 6110 | loss 6.8102 | lr 2.997741e-04
step 6120 | loss 6.2860 | lr 2.997729e-04
step 6130 | loss 6.7234 | lr 2.997717e-04
step 6140 | loss 6.3721 | lr 2.997706e-04
step 6150 | loss 6.5977 | lr 2.997694e-04
step 6160 | loss 6.5672 | lr 2.997682e-04
step 6170 | loss 6.4533 | lr 2.997671e-04
step 6180 | loss 6.4655 | lr 2.997659e-04
step 6190 | loss 6.2058 | lr 2.997647e-04
step 6200 | loss 6.4613 | lr 2.997635e-04
step 6210 | loss 6.6859 | lr 2.997623e-04
step 6220 | loss 6.9313 | lr 2.997611e-04
step 6230 | loss 6.4539 | lr 2.997600e-04
step 6240 | loss 6.5630 | lr 2.997588e-04
step 6250 | loss 6.2761 | lr 2.997576e-04
step 6260 | loss 6.9663 | lr 2.997564e-04
step 6270 | loss 6.6919 | lr 2.997552e-04
step 6280 | loss 6.7421 | lr 2.997540e-04
step 6290 | loss 6.6680 | lr 2.997527e-04
step 6300 | loss 6.7037 | lr 2.997515e-04
step 6310 | loss 6.4918 | lr 2.997503e-04
step 6320 | loss 6.5249 | lr 2.997491e-04
step 6330 | loss 6.5083 | lr 2.997479e-04
step 6340 | loss 6.4392 | lr 2.997466e-04
step 6350 | loss 6.3833 | lr 2.997454e-04
step 6360 | loss 6.7991 | lr 2.997442e-04
step 6370 | loss 6.5390 | lr 2.997430e-04
step 6380 | loss 6.7027 | lr 2.997417e-04
step 6390 | loss 6.6059 | lr 2.997405e-04
step 6400 | loss 6.7242 | lr 2.997392e-04
step 6410 | loss 6.4542 | lr 2.997380e-04
step 6420 | loss 6.2083 | lr 2.997367e-04
step 6430 | loss 6.2291 | lr 2.997355e-04
step 6440 | loss 6.7904 | lr 2.997342e-04
step 6450 | loss 6.6485 | lr 2.997330e-04
step 6460 | loss 6.3973 | lr 2.997317e-04
step 6470 | loss 6.7188 | lr 2.997305e-04
step 6480 | loss 6.3214 | lr 2.997292e-04
step 6490 | loss 6.7983 | lr 2.997279e-04
step 6500 | loss 6.5814 | lr 2.997266e-04
step 6510 | loss 6.4408 | lr 2.997254e-04
step 6520 | loss 6.8950 | lr 2.997241e-04
step 6530 | loss 6.4804 | lr 2.997228e-04
step 6540 | loss 6.1247 | lr 2.997215e-04
step 6550 | loss 6.6045 | lr 2.997202e-04
step 6560 | loss 6.8418 | lr 2.997190e-04
step 6570 | loss 6.4597 | lr 2.997177e-04
step 6580 | loss 6.8689 | lr 2.997164e-04
step 6590 | loss 6.7049 | lr 2.997151e-04
step 6600 | loss 6.3290 | lr 2.997138e-04
step 6610 | loss 6.2967 | lr 2.997125e-04
step 6620 | loss 6.5378 | lr 2.997112e-04
step 6630 | loss 6.3368 | lr 2.997098e-04
step 6640 | loss 6.5400 | lr 2.997085e-04
step 6650 | loss 6.8301 | lr 2.997072e-04
step 6660 | loss 6.1979 | lr 2.997059e-04
step 6670 | loss 6.7940 | lr 2.997046e-04
step 6680 | loss 6.1148 | lr 2.997032e-04
step 6690 | loss 6.5328 | lr 2.997019e-04
step 6700 | loss 6.5423 | lr 2.997006e-04
step 6710 | loss 6.5301 | lr 2.996992e-04
step 6720 | loss 6.5853 | lr 2.996979e-04
step 6730 | loss 6.3059 | lr 2.996966e-04
step 6740 | loss 6.6089 | lr 2.996952e-04
step 6750 | loss 6.4379 | lr 2.996939e-04
step 6760 | loss 6.5199 | lr 2.996925e-04
step 6770 | loss 6.4380 | lr 2.996912e-04
step 6780 | loss 6.6375 | lr 2.996898e-04
step 6790 | loss 6.3018 | lr 2.996885e-04
step 6800 | loss 6.6759 | lr 2.996871e-04
step 6810 | loss 5.8896 | lr 2.996857e-04
step 6820 | loss 6.2125 | lr 2.996844e-04
step 6830 | loss 6.4204 | lr 2.996830e-04
step 6840 | loss 6.5355 | lr 2.996816e-04
step 6850 | loss 6.4426 | lr 2.996803e-04
step 6860 | loss 6.6059 | lr 2.996789e-04
step 6870 | loss 6.2316 | lr 2.996775e-04
step 6880 | loss 6.2889 | lr 2.996761e-04
step 6890 | loss 6.4506 | lr 2.996747e-04
step 6900 | loss 6.6232 | lr 2.996733e-04
step 6910 | loss 6.1016 | lr 2.996719e-04
step 6920 | loss 6.5447 | lr 2.996705e-04
step 6930 | loss 6.3129 | lr 2.996691e-04
step 6940 | loss 6.3826 | lr 2.996677e-04
step 6950 | loss 6.0707 | lr 2.996663e-04
step 6960 | loss 6.2582 | lr 2.996649e-04

KeyboardInterrupt:

In [22]:
import torch
@torch.no_grad()
def generate(model, tokenizer, prompt, max_new_tokens=20, temperature=0.8, top_k=40, device="cuda"):

    model.eval()
    new_tokens = []

    input_ids = torch.tensor(
        tokenizer.encode(prompt).ids,
        dtype=torch.long
    )[None].to(device)

    for _ in range(max_new_tokens):

        logits, _ = model(input_ids)
        logits = logits[:, -1, :] / temperature

        if top_k:
            v, _ = torch.topk(logits, top_k)
            logits[logits < v[:, [-1]]] = -float("inf")

        probs = torch.softmax(logits, dim=-1)
        next_token = torch.multinomial(probs, 1)
        new_tokens.append(next_token)

        input_ids = torch.cat([input_ids, next_token], dim=1)

    return tokenizer.decode(new_tokens)

In [29]:
# checkpoint = torch.load("./checkpoints/best_checkpoint.pt", weights_only=True)
# model.load_state_dict(checkpoint["model_state_dict"])

text = generate(
    model,
    bpe_tokenizer,
    # prompt="""context:\nCO02 использует таблицы AUFK и AFKO для внесения изменений в существующие производственные заказы.
    # \nquestion:\nКакие таблицы CO02 применяет для изменения производственного заказа?
    # \nanswer:\n""", # "Транзакция KSB1 позволяет ", #"Hi how are you",
    prompt="Если МВП в организации тесно связаны с",
    # prompt=samples[303],
    max_new_tokens=50,
    temperature=1,
    top_k=3,
    device="cpu"
)

print(text)

Биография
Родился в семье, в составе, в городе, на территории страны. В результате этого в Москве, в составе, в составе и, в Москве.

В этом, в в городе, в Москве.

В этом году

In [ ]:
# scaler = torch.amp.GradScaler()

# for batch in train_loader:
#     optimizer.zero_grad()

#     with torch.cuda.amp.autocast():  # матричные умножения → float16, softmax → float16, LayerNorm → float32
#         outputs = model(**batch)
#         loss = outputs.loss

#     scaler.scale(loss).backward()  # увеличивает значение на константу
#     scaler.step(optimizer)         # автоматически unscale + проверка overflow
#     scaler.update()                # адаптирует scale

# # 1. Умножает loss на большой коэффициент (например 2¹⁶)
# # 2. Делает backward
# # 3. Делит градиенты обратно перед optimizer.step()
# # 4. Проверяет NaN / inf
# # 5. Автоматически регулирует scale